export default `

La función política de la mentira moderna Alexandre Koyré-Página 1 de 10
” La función política de la mentira moderna por Alexandre Koyré.
1943, revista RENNAISSANCE Revista AEN, N°63. Traducción de M.a José Pozo Sanjuán
Nunca se ha mentido tanto como ahora. Ni se ha mentido de una manera tan descarada, sistemática y constante.
Es posible argumentar que eso no es así, que la mentira es tan antigua como el mundo o, por lo menos, que el hombre mendax ab initio; que la mentira política nació con la ciudad misma, como repetidamente lo evidencia la historia; por último, sin remontarse ya a una era pretérita, que, cuando se produjo el lavado de cerebro de la Primera Guerra Mundial, y junto con la mentira propagandística de la época subsiguiente, se alcanzaron unos niveles y se establecieron unas marcas que muy difícilmente serán superados.
Sin duda, todo esto es verdad; o casi. Es cierto que el hombre se define por la palabra, que es la que soporta la posibilidad de la mentira, y que -sin que ello le desagrade a Porfirio- el mentir, mucho más que reír, es lo propio del hombre. Igualmente, es verdad que la mentira política existe desde siempre; que las reglas y la técnica de lo que antaño se llamaba «demagogia», y hoy es llamado «propaganda», han sido sistematizadas y codificadas desde hace miles de años, y que los productos de esas técnicas, la política de los imperios olvidados y abandonados, nos hablan, todavía hoy, desde lo alto de los muros de Karnak y desde las rocas de Ankara.
Es indiscutible que el hombre ha mentido siempre. Se ha engañado a sí mismo y a los demás. Ha mentido por su propio placer -por el placer de ejercer esa facultad tan sorprendente de «decir lo que no es»-, y de crear, por medio de su palabra, un mundo en el que sólo él es responsable y autor.
Ha mentido también para defenderse: la mentira es un arma. El arma favorita del inseguro y del débil, que, al confundir al adversario, se engrandece y se venga, así, de él.
Pero no vamos a proceder aquí al análisis fenomenológico de la mentira, ni al estudio del lugar que ocupa en la estructura del ser humano: esto nos llevaría demasiado tiempo. Sólo a la mentira moderna y, más concretamente, a la mentira política moderna, en especial, quisiéramos consagrar algunas reflexiones. Ya que, a pesar de las críticas que nos hagan, y de las que nos hacemos a nosotros mismos, estamos convencidos de que en este terreno quo nihil antiquius, la época actual, o más exactamente, los estados totalitarios han innovado poderosamente.
Sin duda, la innovación no es total, y los regímenes totalitarios no han hecho más que llevar al límite ciertas tendencias, ciertas actitudes, ciertas técnicas que existían mucho antes que ellos. Pero no hay nada absolutamente nuevo en el mundo, todo tiene sus fuentes, sus raíces y sus orígenes; y todo fenómeno, todo concepto, toda tendencia, empujados hasta sus extremos, se alteran, se transforman en algo sensiblemente diferente.
Así pues, mantenemos que nunca se ha mentido tanto como se hace hoy en día, y que nunca se ha mentido tan masiva, tan íntegramente como en la
La función política de la mentira moderna Alexandre Koyré-Página 2 de 10
actualidad.
Nunca se ha mentido tanto..., en efecto, día a día, hora a hora, minuto a minuto, se vierten mentiras en el mundo, a raudales. La palabra, los escritos, el periódico, la radio... todo el progreso técnico se ha puesto al servicio de la mentira. El hombre moderno -refiriéndonos de nuevo al hombre totalitario-, se baña en la mentira, respira la mentira, está sometido a la mentira en todo momento de su vida.
En cuanto a la calidad -nos referimos a la calidad intelectual- de la mentira moderna, ha evolucionado en sentido inverso a su extensión. Es comprensible, por lo demás. La mentira moderna -ahí radica su valor distintivo-, está fabricada en serie y se dirige a la masa. Ahora bien, toda producción de masas, es decir y especialmente, toda producción intelectual destinada a la masa, está obligada a rebajar su rasero. Así como no hay nada más refinado que la técnica de la propaganda política moderna, no hay tampoco nada tan burdo como el contenido de sus aserciones, que manifiestan un desprecio tan absoluto y total por la verdad. E incluso por la propia verosimilitud. Desprecio que no es sino igualado, y lo supone además, por el de las facultades mentales de aquellos a los que se dirige.
Podríamos preguntarnos incluso -de hecho, nos lo preguntamos efectivamente-, si tenemos todavía el derecho de hablar aquí de «mentira». Así, el concepto de «mentira» presupone el de la veracidad, de la cual ella es su opuesto y su negación, lo mismo que el concepto de falsedad presupone el de verdad. Ahora bien, las filosofías oficiales de los regímenes totalitarios proclaman unánimemente que la concepción de la verdad objetiva, una para todos, no tiene ningún sentido; y que el criterio de «Verdad» no remite a su valor universal sino a su conformidad con el espíritu de la raza, de la nación o de la clase, su utilidad racial, nacional o social. Prolongando y llevando hasta el extremo las teorías biologicistas, pragmáticas, activistas de la verdad y consumando lo que muy bien se ha llamado «la traición de los intelectuales», las filosofías oficiales de los totalitarismos niegan el valor propio del pensamiento que, para ellos, no es una ilustración sino un arma; su fin, su función, dicen ellos, no es revelarnos la realidad, es decir, lo que realmente es, sino que nos ayudan a modificarla, a transformarla, guiándonos hacia lo que no es. Por todo ello, como ha sido reconocido durante mucho tiempo, el mito a menudo es preferido a la ciencia, y la retórica que se dirige a las pasiones es preferido a la demostración dirigida a la inteligencia.
También en sus publicaciones (incluso en las que se dicen científicas), en sus discursos y, por supuesto, en su propaganda, los representantes de los estados totalitarios se preocupan muy poco de la verdad objetiva. Más fuertes que Dios todopoderoso, transforman a su antojo el presente, e incluso el pasado. Se podría concluir, y se ha hecho a veces, diciendo que los regímenes totalitarios se sitúan más allá de la verdad y de la mentira.
Creemos, por nuestra parte, que eso no tiene importancia. La distinción entre la verdad y la mentira, lo imaginario y lo real, queda bien justificada en el interior mismo de las concepciones y de las estados totalitarios. Es sólo su lugar y su papel los que en cierta manera están intercambiados: los totalitarismos están fundados sobre la primacía de la mentira.
El lugar de la mentira en la vida humana es muy curioso. Los códigos de moral religiosa, al menos en lo que concierne a las grandes religiones universalistas - sobre todo, las que están instauradas en el monoteísmo bíblico-, condenan la mentira de una manera rigurosa y absoluta. Esto es evidente: su Dios, siendo el
La función política de la mentira moderna Alexandre Koyré-Página 3 de 10
de la luz y el de ser, resulta por fuerza el de la verdad. Mentir, esto es, decir lo que no es, deformar la verdad y velar el ser es, por tanto, pecado; e incluso, un pecado muy grave, pecado de orgullo y pecado contra el espíritu, pecado que nos separa de Dios y nos opone a Dios. La palabra de un justo, al igual que la palabra divina, no puede y no debe ser sino verdadera.
Las morales filosóficas, dejando de lado algunos casos de rigor extremo, como los de Kant y Fichte, son en general mucho más indulgentes. Más humanas. Intransigentes en lo que concierne a la forma positiva y activa de la mentira, suggestio falsi, lo son mucho menos en lo que concierne a su forma negativa y pasiva, suppressio veri. Saben que, según el proverbio, «no es conveniente decir siempre la verdad», al menos no se debe decirla siempre ni a todo el mundo.
Mucho más que las morales con base puramente religiosa, las morales filosóficas tienen en cuenta el hecho de que la mentira se expresa por medio de las palabras6 y de que toda palabra se dirige a alguien. No se miente «en el aire». Se miente -cuando se dice o no se dice la verdad- a alguien. Ahora bien, si la verdad es el «alimento del alma», ésta es la de las almas fuertes. Y puede ser peligrosa para los demás. Al menos en estado puro. Incluso puede herirlos. Hay que dosificarla. Diluirla. Revestirla. Además, hay que tener en cuenta las consecuencias del uso que harán a quienes se les diga.
Por tanto, en líneas generales, no existe la obligación moral de decir la verdad a todo el mundo. Y no todo el mundo tiene derecho a exigírnosla.
Las reglas de la moral social, de la moral real que se expresa en las costumbres y que rige, de hecho, nuestras acciones, son mucho más cobardes aún que las de la moral filosófica. Esas reglas, generalmente, condenan la mentira. Todo el mundo sabe que «está feo» mentir. Pero esta condena está lejos de ser absoluta. La prohibición está muy lejos de ser total. Hay casos en los que la mentira se ve permitida, tolerada e incluso recomendada.
Una vez más, el análisis minucioso nos llevaría mucho más lejos. Grosso modo se puede constatar que la mentira es tolerada en tanto que no perjudica el buen funcionamiento de las relaciones sociales, en tanto que «no hace daño a nadie». Está permitida siempre que no lacere el vínculo social que une al grupo, es decir, siempre que se ejerza no en el interior del grupo, entre «nosotros», sino fuera de él: uno no engaña a los «suyos»; en cuanto a los «otros»... lo siento, ¿pero no son precisamente los «otros»?
La mentira es un arma. Por lo tanto, es lícito emplearla para la lucha. Incluso sería estúpido no hacerlo. Por supuesto, a condición de no utilizarla más que contra el adversario y no volverla en contra de los amigos y aliados.
Así pues, a grandes rasgos, se puede mentir al adversario, engañar al enemigo. Hay pocas sociedades, como los maoríes, que sean tan caballerescas como para prohibirse las astucias en la guerra. Hay todavía menos, como los cuáqueros o los wahhabíes, que sean tan religiosos hasta el punto de prohibirse toda mentira con el otro, el enemigo, el adversario. Casi por doquier se admite que el engaño está permitido en la guerra.
La mentira, en líneas generales, no está recomendada en las relaciones pacíficas. Sin embargo (por ser el extranjero un enemigo potencial), la veracidad nunca ha sido considerada como la cualidad preferida de los
La función política de la mentira moderna Alexandre Koyré-Página 4 de 10
diplomáticos.
La mentira es más o menos admitida en el comercio; aún así, las costumbres nos imponen límites que tienen tendencia a hacerse cada vez más estrechos.
No obstante, las costumbres comerciales más rígidas toleran sin protestar la mentira que se reconoce como reclamo. La mentira resulta, pues, tolerada y admitida. Pero precisamente... no debe ser sino tolerada y admitida. En ciertos casos. Hay alguna excepción, como en la guerra, durante la cual, únicamente, utilizarla se convierte en algo justo y bueno.
Pero, ¿y si la guerra, estado excepcional, episódico, pasajero, se convierte en estado perpetuo y cotidiano? Está claro que la mentira, de ser excepcional, pasaría también a ser cotidiana, y que un grupo social que se viera y se sintiera rodeado de enemigos, no dudaría jamás en emplear contra aquellos la mentira. Verdad para los suyos, falsedad para los otros: se convertiría en una regla de conducta, se introduciría en las normas del grupo en cuestión.
Vayamos más lejos. Consumemos la ruptura entre «nosotros» y los «otros». Transformemos la hostilidad de hecho en una enemistad en cierto modo esencial, fundada en la naturaleza misma de las cosas. Sometamos a nuestros enemigos más amenazantes y poderosos. Está claro que todo grupo, situado de esta manera en medio de un mundo de adversarios irreductibles e irreconciliables, vería abrirse un abismo entre ellos y él mismo, un abismo que ninguna vinculación, ninguna obligación social, podría franquear. Parece evidente que en y para un grupo como éste, mentir -mentir a los otros, claro está-, no sería un acto simplemente tolerado, ni siquiera una simple regla de conducta social: se haría obligatorio, se convertiría en una virtud. En cambio, la veracidad fuera de lugar, la incapacidad de mentir, muy lejos de ser considerada como un gesto caballeresco, se convertiría en una tara, un signo de debilidad y de incapacidad.
El análisis tan resumido e incompleto que acabamos de exponer no es -ni mucho menos-, un simple ejercicio dialéctico, un estudio abstracto de una posibilidad puramente teórica. Sino al contrario: no hay nada más concreto y más real que los grupos sociales cuya descripción esquemática hemos intentado esbozar. No sería difícil dar, ni incluso multiplicar, ejemplos de sociedades cuya estructura mental presenta, en varios planos, los rasgos fundamentales o, si se prefiere, la perversión fundamental que acabamos de señalar.
Ahora bien, estos niveles, a los que por otro lado hemos seguido en escala ascendente, expresan, según nos parece, la acción de tres factores:
1)	El grado de alejamiento y de oposición entre los grupos en cuestión. Existe, lejos de la hostilidad natural por el extranjero, enemigo potencial e incluso enemigo real, un odio sagrado que inspiran los combatientes en una guerra religiosa; y, lejos de aquella también, la ferocidad biológica que anima a los que participan en una guerra de exterminación racial.
2)	La relación de fuerzas, es decir, el grado de peligro que amenaza al grupo estudiado por parte de sus vecinos-enemigos. La mentira, ya lo hemos dicho, es un arma, y sobre todo, el arma del más débil: no se emplea la astucia contra los que es fácil aplastar sin grandes riesgos: se actuará con astucia, se engañará al contrario para poder escapar del peligro.
3)	El grado de frecuencia de contactos entre los grupos hostiles y sus miembros. En efecto, si estos grupos, sea cual sea su grado de hostilidad, no
La función política de la mentira moderna Alexandre Koyré-Página 5 de 10
entran nunca en contacto, o sólo en el campo de batalla, si los miembros de un grupo no frecuentan nunca la sociedad de los otros, tendrán, fuera del ardid guerrero, rara ocasión de mentir a éstos. La mentira presupone el contacto; implica y exige el intercambio.
Este último comentario nos obliga a dejar de lado el análisis para más adelante. Suprimamos la existencia autónoma de nuestro grupo. Sumerjámonos por completo en el mundo hostil de un grupo extranjero, adentrémonos en el seno de una sociedad enemiga, con la que, sin embargo, entramos en contacto diariamente: está claro que en y para el grupo en cuestión, la facultad de mentir será mucho más necesaria, y la virtud de mentir más apreciada que la presión exterior, que la tensión entre «nosotros» y los «otros», que la enemistad de los «otros» hacia «nosotros», que la amenaza que esos «otros» hacen pesar sobre «nosotros», crecerá y aumentará de intensidad.
Llevemos todo hasta el límite; hagamos crecer la hostilidad hasta volverla absoluta y completa. Está claro que el grupo social del que estamos a punto de seguir sus avatares se encontrará obligado a desaparecer. A desaparecer de hecho, o bien, aplicando hasta el extremo la técnica y el arma de la mentira, a desaparecer a los ojos de los otros, a escapar de sus adversarios y eludir su amenaza refugiándose en la oscuridad del secreto.
El cambio de posición, en adelante, será absoluto: la mentira para nuestro grupo, convertido en grupo secreto, será más que una virtud. Se convertirá en la condición de su existencia, en su modo cotidiano de ser, el fundamental y prioritario.
Por el mero hecho de ser secreto, ciertos rasgos característicos propios de todo agregado social se encontrarán acentuados y exagerados fuera de toda medida. Así, por ejemplo, todo grupo erige una barrera más o menos permeable y salvable entre él mismo y los otros; todo grupo reserva para sus miembros un trato privilegiado, establece entre ellos un cierto grado de unión, de solidaridad, de «amistad»; todo grupo atribuye una particular importancia al mantenimiento de ciertos límites de separación entre él y los «otros», y por tanto, a la salvaguardia de elementos simbólicos que forman, de algún modo, su contenido; todo grupo, el vivente al menos, considera la pertenencia al grupo como un privilegio y un honor, y ve en la fidelidad a su grupo un deber para con sus miembros. Cualquier agregado social, por lo tanto, desde que se consolida y consigue una cierta expansión, implica una cierta organización, una cierta jerarquía.
Todos esos rasgos aparecen exasperados en una agrupación secreta; la barrera, permaneciendo en ciertas condiciones franqueable, se vuelve impermeable, la integración en el grupo se convierte en una prueba iniciática irrevocable, la solidaridad se transforma en una dependencia apasionada y exclusiva; los símbolos adquieren un valor sagrado, la fidelidad al grupo se convierte en el deber supremo, a veces incluso único, de sus miembros; en cuanto a la jerarquía, convirtiéndose en secreta, adquiere también ella misma, un valor absoluto y sagrado; la distancia entre sus escalafones aumenta, la autoridad se vuelve ilimitada y la obediencia perinde ac cadaver  es la regla y la norma de las relaciones entre el miembro del grupo y sus jefes. Pero todavía hay más. Toda sociedad secreta, bien sea un grupo de doctrina o bien de acción, una secta o una conspiración -y, por lo demás, siendo bastante difícil trazar el límite entre estos dos tipos de grupos, pues el grupo de acción será, o se convertirá casi siempre, en un grupo de doctrina-, es un grupo secreto o
La función política de la mentira moderna Alexandre Koyré-Página 6 de 10
incluso de secretos. Queremos decir que, aún cuando sea un mero grupo de acción, como una banda de gansters o una conspiración de pasillos, no posee rasgos de doctrina esotérica y secreta en la que esté obligado a salvaguardar los misterios escondiéndolos a los ojos de los no iniciados, y su existencia misma está indisolublemente ligada al mantenimiento de un secreto e incluso de un doble secreto; del secreto de su propia existencia al igual que el de los fines de su acción.
Por todo ello, el deber supremo del miembro del grupo secreto, el acto con el que expresa su afinidad y su fidelidad a éste, el acto por el cual se afirma y se confirma su pertenencia a dicho grupo, consiste, paradójicamente, en la disimulación de este hecho. Disimular lo que se es, y, para poder hacerlo, simular lo que no se es: ahí radica, pues, el mecanismo de subsistencia que, necesariamente, cualquier sociedad secreta impone a sus miembros.
Disimular lo que se es, fingir lo que no se es... Esto implica, sin lugar a dudas, no decir -nunca- lo que se piensa ni lo que se cree, y también decir -siempre- lo contrario. Así, para todo miembro de un grupo secreto, la palabra no es más que un medio para ocultar su propio pensamiento. Por lo tanto, todo lo que dicen es falso. Toda palabra, al menos todo discurso en público, es mentira.
Sólo las cosas que no dicen o al menos que no revelan más que a los «suyos» pueden, o no, ser verdad.
La verdad resulta, pues, siempre esotérica y oculta. Nunca es accesible al común, al profano. Ni siquiera lo es para el que no está completamente iniciado.
Todo miembro de una agrupación secreta, digno de su papel, tiene plena consciencia de ello. Por lo tanto, jamás creerá lo que oiga decir en público por un miembro de su propia asociación, y sobre todo, no admitirá jamás como verdadero algo que sea públicamente proclamado por su jefe. Ya que no es a él a quien se dirige su jefe, sino a los «otros», a esos «otros» a quienes tiene el deber de cegar, estafar, engañar. Y, entonces -de nuevo con una paradoja-, sólo en el rechazo de creer en lo que dice y proclama se expresa la confianza del miembro del grupo en su jefe.
Sin duda, podría objetarse que nuestro análisis, tan justo como sea, se aleja de su objeto. Los gobiernos totalitarios no son, desgraciadamente, ni más ni menos que sociedades secretas, rodeadas de enemigos amenazantes y poderosos, y se ven obligados, por este hecho, a buscar la protección de la mentira, a esconderse, a disimular. E incluso los «partidos únicos» que forman el armazón de los regímenes totalitarios, no pueden, nos dirán, tener nada en común con los grupos de conspiradores: operan en pleno día. También, lejos de querer encerrarse, y levantar una barrera entre ellos mismos y los otros, su fin, reconocido y patentado, es precisamente el de absorber a todos esos «otros», englobar y abarcar a la nación (o a la raza) entera.
Por otra parte, cabría discutir el vínculo que pretendemos establecer entre totalitarismo y mentira. Podríamos valorar que, aunque lejos de ocultar y disimular los fines cercanos y lejanos de sus acciones, los gobiernos totalitarios siempre los han proclamado urbi et orbi (para lo que ningún estado democrático ha tenido nunca el valor), y que es ridículo acusar de mentir a alguien que como Hitler anunció públicamente (e incluso lo imprimió, negro sobre blanco, en Mein Kampf ) el programa que a continuación realizó punto por punto.
Todo lo cual, sin duda, es acertado; pero sólo en parte. Y por ello las objeciones
La función política de la mentira moderna Alexandre Koyré-Página 7 de 10
que acabamos de formular no nos parecen de ninguna manera decisivas.
Es verdad que Hitler (como los otros caudillos de estados totalitarios), anunció todo su programa de acción públicamente. Pero, precisamente porque sabía que no sería creído por los «otros», que sus declaraciones no serían tomadas en serio por los no iniciados, precisamente así, diciéndoles la verdad, estaba seguro de engañar y adormecer a sus adversarios. Sería, pues, ésta una vieja técnica maquiavélica de la mentira en segundo grado, técnica perversa por antonomasia, y en la que la verdad misma se convierte en puro y simple instrumento de engaño. Parece claro que la tal «verdad» no tiene nada que ver con la verdad.
También es cierto que ni los estados ni los partidos totalitarios son sociedades secretas en el sentido mismo del término y que actúan públicamente. E incluso con gran respaldo de publicidad; y es que justamente en esto consiste la innovación de la que tanto hemos hablado. Son conspiraciones a la luz del día.
Una conspiración en pleno día -forma nueva y curiosa de un grupo de acción, propia de la época democrática, de la época de civilización de masas-, no está rodeada de amenazas, ni tiene, pues, necesidad de disimular. Más bien al contrario, estando obligada a hacer reaccionar a las masas, a ganarse a la gente, a englobar y organizar el mundo, necesita aparecer a la luz, e incluso a concentrar esa fuerza sobre sí mismos y sobre sus cabecillas. Ni siquiera los agrupados necesitan esconderse; al revés, pueden exhibir su pertenencia al grupo, al «partido», pueden hacerlo visible y reconocible a los otros e incluso por sus símbolos exteriores, emblemas, insignias, brazaletes o uniformes, o por sus gestos rituales consumados en público. Pero mientras que los miembros de una sociedad secreta -y a pesar del hecho, ya mencionado, de que la conspiración en pleno día tiende a convertirse en una organización de masas-, guardarán una distancia entre ellos y los otros; la adopción de signos exteriores de pertenencia al «partido» no hará más que acentuar la oposición y hacer más sólida la barrera que les separa de los de fuera; la fidelidad al grupo será la virtud principal de sus miembros; la jerarquía interna del «partido» adquirirá el aspecto y tendrá la estructura de una organización militar, y la regla non servatur fides infidelibus será aún más escrupulosamente observada. Ya que la conspiración a la luz del día, si no corresponde a una sociedad secreta, es al menos propia de una sociedad con secreto.
La victoria, es decir, el éxito de la conspiración, no destruirá los rasgos que acabamos de citar; se limitará a debilitar a algunos, aunque, en cambio, fortalecerá a otros y particularmente, reforzará el sentimiento de superioridad de la nueva clase dirigente, su convicción de pertenecer a una élite, a una aristocracia integramente separada de la masa.
Los regímenes totalitarios no son sino conspiraciones, resultantes del odio, el miedo, la envidia, nutridas por un deseo de venganza, de dominación, de rapto; confabulaciones que han conseguido, o mejor, y ese es un punto importante, que han logrado parcialmente el éxito, que han conseguido imponerse en su país hasta conquistar el poder, adueñándose del Estado. Pero que no han logrado -todavía- realizar los fines que se han propuesto, y, precisamente por ello, continúan conspirando.
Podríamos preguntarnos si el concepto de conjurar a la luz del día no es una contradicción in adjecto. Una conspiración implica misterio y secreto. ¿Cómo podría hacerse a la vista de todos?
La función política de la mentira moderna Alexandre Koyré-Página 8 de 10
Sin duda. Toda confabulación implica un secreto; secreto que concierne precisamente a los fines de sus actuaciones, fines que debe disimular justamente para poder alcanzarlos y que no son conocidos sino a quienes les concierne. Pero la conspiración a la luz del día no es una excepción a la regla, ya que, como decimos, no siendo una sociedad secreta propiamente dicha, es de todas maneras una sociedad con secreto.
¿Cómo una sociedad de este tipo, es decir, una sociedad que actúa en la plaza pública , que busca organizar a las masas, y cuya propaganda se dirige a las masas, podría mantenerse en secreto? La pregunta es completamente legítima. Pero la respuesta no es tan difícil como parecería en principio. Es incluso bastante simple, porque sólo hay un medio de guardar un secreto: el de no revelarlo o el de revelarlo sólo a quienes confiamos, a una élite de iniciados. Ahora bien, en una conspiración a ojos vistas, esta élite, que únicamente está volcada a los fines reales del complot, está formada naturalmente por los jefes, los dirigentes del «partido». Y como éste ejerce una acción pública y sus jefes reaccionan en público y están obligados a exponer públicamente su doctrina, hacer discursos públicos y declaraciones públicas, resulta que el mantenimiento del secreto implica la aplicación constante de esta regla: toda aserción pública es un criptograma y una mentira; una aserción doctrinal tanto como una promesa política, una teoría o fe oficial tanto como una obligación contraída por compromiso.
Non servatur fides infidelibus sigue siendo la regla suprema. Los iniciados lo saben. Los iniciados y los que son dignos de serlo. Comprenderán, descifrarán y traspasarán el velo que enmascara la realidad.
Los otros, los adversarios, la masa, incluida la masa de adherentes al grupo, aceptarán como verdades las aserciones públicas, y por ello mismo, se revelarán indignos de recibir la verdad secreta y de formar parte de la élite.
Los iniciados, los miembros de la élite -y todo ello, merced a una especie de saber intuitivo y directo- participan del pensamiento íntimo y profundo del jefe, conocen los fines secretos y reales del movimiento. De modo que no se sienten confundidos por las contradicciones y las inconsistencias de sus aseveraciones públicas: saben que tienen como fin defraudar a la masa, a los adversarios, a los «otros», y admiran al jefe que maneja y practica con maestría la mentira.
En cuanto a los otros, a los que los creen, demuestran por este mismo hecho que son insensibles a la contradicción, impermeables a la duda e incapaces de pensar.
La actitud espiritual que acabamos de describir, actitud que corresponde a todos los estados totalitarios -y sobre todo, claro está, al régimen totalitario por excelencia, es decir, el régimen hitleriano-, implica, evidentemente, una concepción del hombre, una antropología. Sin embargo, aunque antítesis de la antropología democrática o liberal, la antropología totalitaria no estriba de ninguna manera en un cambio de valores que, rebajando el pensamiento, la inteligencia, la razón, sitúa en la cima del ser humano las fuerzas oscuras, «telúricas», del instinto y de la sangre. Sin lugar a dudas, la antropología totalitaria insiste en la importancia, el papel y la primacía de la acción. Pero de ningún modo desprecia la razón. O por lo menos, lo que desprecia -o más exactamente, lo que aborrece-, no son sino sus más altas formas, la inteligencia intuitiva, el pensamiento teórico, el nous como lo llamaban los griegos. En cuanto a la razón discursiva, la razón razonante y calculadora, realmente su valor no es desdeñado en absoluto. Todo lo contrario. La sitúa en
La función política de la mentira moderna Alexandre Koyré-Página 9 de 10
una cima tan alta que la hurta al común de los mortales.
En la antropología totalitaria, el hombre no se define por el pensamiento, la razón o el juicio, justamente porque, según aquélla, la inmensa mayoría de los hombres está desprovisto de ellos. Por otro lado, ¿podemos seguir hablando de hombre? De ninguna manera. Ya que la antropología totalitaria no admite la existencia de una esencia humana única y común a todos37. Entre un hombre y «otro hombre» no habría diferencia, una diferencia de grado, sino una diferencia de naturaleza. La vieja definición griega que designa al hombre como un zoon logicon, descansa en un equívoco: no hay relación necesaria entre logos -razón y logos -palabra, como tampoco existe medida común entre el hombre, animal razonable y el hombre, animal que habla. Ya que el animal hablante es ante todo un animal crédulo, y el animal crédulo es precisamente el que no piensa.
A su juicio, el pensamiento, es decir la razón -discernimiento de lo verdadero y lo falso, decisión y juicio-, se estima como algo raro y muy poco extendido en el mundo: sería un asunto de la élite y no de la masa. Y esta última se ve guiada o, mejor, movida por el instinto, la pasión, por los sentimientos y resentimientos. En ella, no sabe pensar. Ni querer. No sabe sino obedecer y creer39.
Y cree todo lo que oye. Con tal de que se lo digan con suficiente insistencia.
Con tal de que halaguen sus pasiones, sus odios y sus pavores. Por lo tanto, es inútil intentar permanecer más acá de los límites de la verosimilitud: al contrario, cuanto más descarada, masiva y cruelmente se miente, mejor se será creído y seguido. Resulta inútil igualmente intentar evitar la contradicción: la masa nunca la percibirá; es inútil hacer concordar lo que se dice a unos con lo que se cuenta a los otros: nadie creerá lo que se comenta a los otros, y todo el mundo creerá lo que se le dice a él; es inútil aspirar a la coherencia: la masa carece de memoria; es inútil disimularles la verdad: es radicalmente incapaz de percibirla; es inútil incluso esconderles que se la engaña; no comprenderá jamás que se trata de eso mismo, que se trata del tratamiento al que se la somete.
Toda la antropología a la que nos referimos está en la base de la propaganda de los miembros de esa conspiración a la luz del día: y el logro mismo que le acompaña explica el desprecio literal y sobrehumano de los totalitarios -nos referimos a los miembros de la élite que sabe- por la masa, tanto por la que forman sus adversarios, como la que constituyen sus adherentes, es decir, por todos los que les creen y les siguen; y asimismo por todos los que, sin seguirles, les creen. No vamos a contestar al fundamento de esta actitud. Nos parece suficientemente justificada. Por lo demás, los representantes y los jefes de los regímenes totalitarios están bien situados como para poder juzgar el valor intelectual y moral de sus adherentes, de sus estafados.
Nos limitaremos a constatar simplemente que si el triunfo de la conspiración de los totalitarios puede considerarse como un prueba experimental de su doctrina antropológica así como de la perfecta eficacia de sus métodos de enseñanza y de educación basados en la mentira, esta experiencia no sirve más que para sus propios países y para sus pueblos. No sirve para los demás y, notablemente, no vale para los países democráticos que, después de todo, obstinados e incrédulos, se han mostrado reacios a la propaganda totalitaria: pues, en esos países, esta propaganda, aunque sostenida por pequeñas conjuras locales, no ha podido, en fin de cuentas, equivocar sino a una parte de
La función política de la mentira moderna Alexandre Koyré-Página 10 de 10
la sedicente «élite social».
De modo que, y por una última paradoja -que en el fondo no es más que una sola-, precisamente las clases populares de los países democráticos, de esos países pretendidamente degenerados y bastardos, se han revelado como pertenecientes a una categoría superior de la humanidad, de estar compuestas por hombres inteligentes, según los principios mismos de la antropología totalitaria, y son, en cambio, los seudo-aristócratas totalitarios, los que representan su categoría inferior, la del hombre crédulo que no logra pensar.
( Revista AEN, N°63. Traducción de M.a José Pozo Sanjuán



`;


