import xs, { Stream } from 'xstream';
import { VNode } from '@cycle/dom';

export function Ale(sources: {}) {

  const ale: Stream<VNode>[] = [];

  return {
    DOM: view(ale)
  };
}

function view(doms: Stream<VNode>[]) {
  return xs.combine(...doms)
    .map(ale =>
      <div className='pure-g'>
      <style jsx>{`
p, ul, ol {font-size: 110%; font-weight: bold; color: #190D54;}.sub {color: #190D54; background:#DDD6FE} .no {color: #252527; background:#EDDCDC} .subGreen {color: #186A26; background:#BCE9C2}.subOr {color: #A17413; background:#ffeaea} .humor {color: #903211; background:#ffeaea} .coment {font-size:90%; font-weight: bold; font-style: italic; color: #0F4747;} blockquote .sum{font-size: 100%; font-weight: bold; color: #F7F6F9;background-color: lightblue; padding: 10px; border: 1px solid #4CAF50;} .pag {font-size: 70%;color: #2C9494; }
.sum{background-color: lightblue; padding: 10px;} aside {font-size: 15px; display: block; padding: 10px; border: 1px solid #4CAF50; padding-left:50px} .item-aside { width: 4 / 12 * 100%; position: absolute; z-index: -1; top: 0; right: 0; padding-left: 10px * 2 + 1px; padding-right: 10px; opacity:0;transition: all 400ms; // left line &::after { content: '';position: absolute; top: 0; bottom: 0; left: 10px; border-left: 1px #ddd solid; } &:hover { z-index: 1; opacity: 1; }}`}</style>
        <div className='pure-u-1-1'>
        <div className=" article-info"><div className=" breadcrumb"><div className=" suplement"><a href="https://www.pagina12.com.ar/secciones/el-pais/notas">El país</a></div><div className=" topic"></div></div><div className=" time"><span datetime="2017-01-12" pubdate="pubdate">12 de enero de 2017</span></div></div>
        <div className=" article-titles"><div className=" article-prefix">Opinión</div><div className=" article-title"><h1>El momento político del ¿Qué hacer?</h1></div></div>
<div className=" article-text"><p>Escuchando hablar a los portavoces del Frente de Izquierda, todo lo que describen del momento político argentino actual se presenta como “objetivamente” cierto. Pero de inmediato estas mismas certezas pertenecen a un orden de generalidad del tipo “el capital se sostiene de la extracción de plusvalía de la fuerza de trabajo bajo su condición de mercancía”, etc . Son expresiones irrefutables para aquellos que reconocemos en Marx el que desentrañó la ley que rige a la sociedad moderna. Y que podemos resumir así: todo lo que “es” en el mundo contemporáneo se presenta bajo el modo de la “mercancía”. La mercancía, tal como el genio de Marx fue capaz de desentrañar no es un objeto material, es una estructura portadora de un jeroglífico social que vehiculiza el modo en que las relaciones sociales de producción se ocultan y desenvuelven. Es lo que clásicamente nombró Marx como “fetichismo de la mercancía”. Pero éste es un hecho de estructura que no permite una derivación política inmediata.&nbsp;</p>
<p>El momento político del ¿qué hacer? Es inevitable. Y siempre, de algún modo vivimos bajo el duelo de esa pregunta. El Frente de Izquierda no parece reconocer ese duelo, cuestión crucial, especialmente cuando el neoliberalismo ha logrado superar la “alienación” y ya produce subjetividades a su medida. El Frente de Izquierda elude esta cuestión situándose como representando directamente a los explotados y eludiendo cualquier lectura política de lo que implica la estructura actual del poder neoliberal contemporáneo.</p>
<p>Cuando homologa el kirchnerismo, Massa, Macri, como representantes de los mismos intereses del capital y la burguesía. El corolario inmediato de esta posición es que ellos representan directamente a los trabajadores, sin mediación política alguna en la “evidente” lucha de clases. Pero la lucha de clases no existe de un modo natural y endógeno en el interior del Capital. Hay que construirla políticamente sobre los antagonismos instituyentes que siempre son contingente y no se dan necesariamente de forma mecánica.</p>
<p>Tal vez sería interesante que los militantes de dicha organización se dieran una vuelta por Gramsci y Laclau, eso les permitiría pensar de otro modo la construcción de una “clase hegemónica”, construcción que no emana directamente de las “relaciones sociales de producción” y que exige la articulación de una voluntad popular, que excede el marco de la relación capital-trabajo y que incluye exclusiones, segregaciones, inmigrantes, desempleados estructurales de tipos diversos. Y que además puedan &nbsp; reconocerse en sus distintos legados, herencias y linajes simbólicos. Al no admitir esta cuestión central y volver todo equivalente se constituyen en la izquierda clásica que denuncia todo sin volverse nunca una amenaza real para el sistema. Por ello, sería importante que pudieran reconocer aquellos aspectos del kirchnerismo que fueron antagónicos y se plantearán una alianza crítica con el mismo. ¿Es posible que un militante que se autodefine de izquierda pueda desconocer la política de la memoria llevada adelante en los años kirchneristas, política que no encuentra ningún caso similar en el mundo?</p>
<p>Para ello deberían revisar su marxismo esencialista y testimonial para ingresar al arduo problema de cómo se construye una mayoría popular capaz de gobernar en un sentido contrahegemónico al poder neoliberal.</p>
<p>Así como Sartre llegó a proclamar que el marxismo era la “filosofía irrebasable de nuestro tiempo”, el marxismo de nuestra época, tiene su punto de partida, el principio del problema y no su solución, en el populismo de izquierda. Único modo de indagar la lógica emancipatoria aún por venir.</p>
</div>
<hr></hr>
<div className=" article-info"><div className=" breadcrumb"><div className=" suplement"><a href="https://www.pagina12.com.ar/secciones/contratapa/notas">Contratapa</a></div><div className=" topic"></div></div><div className=" time"><span datetime="2017-03-13" pubdate="pubdate">13 de marzo de 2017</span></div></div>
<div className=" article-titles"><div className=" article-title"><h1>La pregunta por el comunismo</h1></div></div>
<div className=" article-text"><p>La palabra comunismo ha vuelto a ingresar en la escena teórica de distintos pensadores, que podríamos designar como “radicales”. En todos ellos encontramos un rasgo similar que insiste de distintos modos: la cada vez más evidente incompatibilidad entre el Poder del Capital y la organización democrática de la sociedad.</p>
<p>Por supuesto, no es demasiado difícil aceptar que el Capital siempre intenta presentarse bajo la forma de, como dirían los franceses, un “semblante” democrático. Aún cuando cada vez es más patente el carácter de reproducción ilimitada del Capital, reproducción que en sus efectos más logrados no respeta ningún vínculo social, sin embargo la máscara democrática se emplea siempre, incluso en el caso mismo de Trump.</p>
<p>Desde esta lógica, lo que plantea Badiou, a veces Zizek, a veces los comunistas italianos, es separarse radicalmente de la forma Estado y destruir el semblante parlamentario, electoral y del Estado de Derecho que encubre al Capitalismo en su poder imperial. Por esta pendiente, una política “anticapitalista” exigiría destruir lo que Badiou denomina el “capital-parlamentarismo”, verdadera coartada del Capital y auténtico obstáculo para cualquier lógica política con vocación emancipatoria.</p>
<p>Algunos &nbsp;marxistas, cuando apelan a la lucha de clases, pretenden dar a entender que con esto se nombra la posición más “radical”, la “más de izquierda”. Sin embargo, ¿no merece el termino en cuestión &nbsp;ser vuelto a indagar?, ¿no sería conveniente volverlo a indagar desde la perspectiva de nuestra contemporaneidad? Sería especialmente relevante plantearse estas cuestiones a partir de cómo se gestan los verdaderos antagonismos en lo social.</p>
<p>En cualquier caso, este interrogante demanda una aclaración de entrada: nuestro punto de partida es que primero está siempre el antagonismo, de un modo estructural y constitutivo y luego lo social, que se organiza &nbsp; alrededor del mismo. No existe una sociedad que primero haya sido armónica, neutral o con algún conflicto que otro o alguna anomalía a resolver. Por el contrario, a raíz de cómo el discurso estructura lo social, este siempre lo hace a partir de una negatividad o brecha antagónica que no se puede cancelar dialécticamente.</p>
<p>En el capitalismo, uno de los antagonismos más importantes es el formulado por Marx, el que se gesta entre el Capital y la renta de trabajo. Sin duda, la plusvalía sigue siendo el aspecto fundamental del Capitalismo, pero su apropiación ya no sólo se circunscribe a la forma Capital-Trabajo. Existen millones de seres humanos que no trabajarán nunca, desempleados estructurales, trabajadores en negro, nuevos esclavos, trabajadores nómadas, clandestinos, etc. En todos los casos, es un hecho que la apropiación de plusvalía, por distintas vías, se realiza como tal. ¿Se puede unificar todo este campo bajo el concepto de lucha de clases? Como si el termino en sí mismo poseyese la cualidad metafísica no solo de totalizar elementos absolutamente heterogéneos, como los antes mencionados, sino que también pudiese animarlos y ponerlos en marcha en una determinada dirección de la historia que fuera a &nbsp;llevar el capitalismo a su fin.</p>
<p>¿Puede un verdadero materialista seguir pensando de este modo? Sólo se explica si se quiere a toda costa, se lo reconozca o no, mantener el espejismo moderno &nbsp;del progreso en la historia. Para ello, es necesario dotar a la llamada lucha de clases de un poder que nunca se confirma, &nbsp;salvo cuando un antagonismo sea habitado por la “parte que no tiene parte” &nbsp;en la vida institucional o social y logre alcanzar la forma de una organización colectiva. No obstante, en este caso, la lucha de clases no es más que la designación simbólica y secundaria &nbsp;de un antagonismo constituyente de lo social. En cambio, dar por constituida de entrada a la lucha de clases y otorgarle una dinámica inmanente y sin mediación política alguna, que va a ser capaz de desconfigurar al Capitalismo en su funcionamiento hiperconectado y homogéneo, es un error teórico y político.</p>
<p>Por esto, es muy importante, para cualquier intento de renovación del marxismo o del materialismo emancipador, establecer que no existe una relación “necesaria” entre la explotación (incluyendo los diferentes modos de extracción de plusvalía) y la emergencia de un sujeto histórico, que dirija la salida del capitalismo. No es que no exista actualmente, es que nunca existió en la realidad un proceso semejante. Un materialismo emancipador, debería admitir, que no existe una relación de complementariedad entre la explotación que la forma mercancía siempre impone y los seres humanos sometidos a la misma.</p>
<p>La lucha de clases en su versión esencialista ha contribuido a consolidar ese fantasma de complementariedad y reciprocidad que asegura que entre los explotadores y los explotados existe una relación “dialéctica” que en algún momento quedará superada. La relación entre el Capital y &nbsp;“las existencias sexuadas, mortales y hablantes” no existe, en el sentido en que sólo cumple la función de reproducir ilimitadamente el Uno del Capital.&nbsp;</p>
<p>Solo construyendo un suplemento &nbsp;político que desconecte las relaciones &nbsp;distribuidas por el mercado, puede surgir el deseo de no seguir siendo explotado y darle una inscripción simbólica a ese Deseo. En suma, no basta con ser explotado, hay que poder desear dejar de serlo y esto no viene garantizado por ningún automatismo histórico. Ese deseo no surge de ninguna dinámica interna al capitalismo, ni de ninguna relación dialéctica de la lucha de clases. Surge del sujeto, porque él mismo, desde su primera inscripción simbólica, está constituido de un modo antagónico. Ese sujeto que surge siempre fracturado y en falta, porque lo constituye un lenguaje que, sin embargo, nunca lo nombra del todo.</p>
<p>Es en este “uno por uno” del sujeto irreductible a cualquier determinación que lo pretenda agotar en una definición concluyente, donde puede surgir &nbsp;la voluntad colectiva de querer otra cosa que lo que el poder del Capital &nbsp;propone para su vida.</p>
<p>No obstante, para que un debate como este fuese lo suficientemente explícito, una aclaración sería pertinente: para establecer las condiciones de ese Comunismo, que cómo indican correctamente estos pensadores, no advendría como resultado de ninguna ley histórica, ¿qué tipo de prácticas políticas deberían surgir y en qué estilo de confrontación deberían plantearse las mismas? ¿Cómo se destruiría el falso semblante del “capital-parlamentarismo”? ¿Qué tipo de guerra habría que asumir y qué tipo de violencia sería necesario afrontar para la supuesta ocupación de los lugares de lo “Común “por fuera del Estado.</p>
<p>Por supuesto, en todos estos &nbsp;autores “comunistas” existe una cláusula de reserva con respecto a aquellos movimientos latinoamericanos que ocuparon el Estado. Se niegan, en la mayor parte de los casos, a admitir que se puede estar en el Estado para ir mas allá de el mismo.</p>
<p>Badiou, uno de los defensores más lúcidos de la llamada “hipótesis comunista”, lo dice con todas las palabras que corresponden a esta idea: se trata de destruir al Estado para, por fin, acceder a lo real del Capital. Sin duda, en este esquema de pensamiento, aunque se haya renunciado al sentido finalístico de la Historia, aún permanece la idea de la ruptura absoluta propia del lenguaje de la Revolución.</p>
<p>Por último, quienes estarían de nuevo dispuestos al sacrificio heroico para lograr lo que Pasolini llamó en su día una “religión verídica” ¿qué precio tendrían que pagar por hacer renacer de las cenizas de la Historia la experiencia comunista?</p>
<p>Si no se habla de esto y se condena cualquier experiencia que se introduzca en el barro “populista” del Estado, como insuficiente, que además, por razones estructurales siempre lo es la formulación de la hipótesis comunista, se mantiene aún en el campo de la especulación filosófica. Pero admitamos las buenas intenciones, aún insistentes en estos pensadores, sobre la condición humana, en una época donde su espectro apocalíptico planea con más fuerza que nunca.</p>
</div>
<hr></hr>
<div className=" article-info"><div className=" breadcrumb"><div className=" suplement"><a href="https://www.pagina12.com.ar/secciones/contratapa/notas">Contratapa</a></div><div className=" topic"></div></div><div className=" time"><span datetime="2017-06-05" pubdate="pubdate">05 de junio de 2017</span></div></div>
<div className=" article-titles"><div className=" article-title"><h1>¿Qué es la subjetivación neoliberal?</h1></div></div>
<div className=" article-text"><p>Una vez más, en su último libro "La pesadilla que no acaba nunca" Christian Laval y Pierre Dardot profundizan su analítica del neoliberalismo en su nueva extensión planetaria. Siguiendo una tradición foucaultiana, estos autores no ven al neoliberalismo como exclusivamente un “mal” de los mercados financieros que tendrían como cometido destruir el espacio público. Más bien, <span className="sub">el neoliberalismo es un nuevo orden racional que va borrando tendencialmente la diferencia público-privado y que dispone de la potencia de apropiarse de los distintos órdenes de la vida hasta llegar a configurar el modo más íntimo de la vida del sujeto</span>. Para estos autores, funciona una suerte de <span className="sub">promesa neoliberal que en su ejercicio cautivante constituye a los sujetos en su propio modo de ser</span>.</p>
<p>En el capítulo denominado “la ilimitación de la subjetividad”, reconociendo la clara inspiración en la tesis de Lacan indagan el modo en que la condición primordial “ilimitada” del neoliberalismo se introduce en la vida de los seres hablantes. Por condición ilimitada, estos autores, al igual que Lacan, admiten que <span className="sub">el nuevo capitalismo no puede ser intervenido ni regulado por ningún exterior. Su potencia conectora, abarcadora e interventora en la propia conformación de los lazos sociales es imposible de limitar</span>. ¿En qué afecta esto a los sujetos?, ¿cómo interviene esta potencia ilimitada en la propia constitución de los sujetos?</p>
<p>En primer lugar, los autores insisten que el neoliberalismo ha sabido construir un “imaginario” al que no se le ha podido contraponer un mundo alternativo por parte de la izquierda. Lo que le otorga al neoliberalismo su carácter de promesa y seducción es que a través de distintos dispositivos acompañados por “coachs” de distinto tipo y managers del alma de diferentes cuños y estilos han introducido una lógica de rendimiento y de “autovaloración de sí” donde el sujeto solo es una voluntad de acumulación del propio valor. Aunque los autores no citen a Heidegger, esta cuestión evoca claramente su lectura de la Técnica en conjunción con la Voluntad de Poder, esa voluntad que sólo anhela aumentarse a sí misma indefinidamente.</p>
<p>En el neoliberalismo los sujetos no sólo venden su fuerza de trabajo bajo la forma Mercancía, también existe algo que compromete al propio ser con un “capital humano” y un “espíritu empresarial” que lleva a la existencia misma a comportarse como una empresa. No se trata de tener una empresa ni de trabajar en ella, sino de existir bajo el mandato de convertirse a sí mismo y a la propia relación con uno mismo en capital financiero. Laval y Dardot enmarcan esta operación en la fórmula (S-S’) donde el sujeto se engendra a sí mismo ilimitadamente en capital financiero y el capital financiero en sujeto. En efecto, se trata de un movimiento circular tal como Lacan describe el funcionamiento del Discurso Capitalista. En este aspecto, señalemos que <span className="sub">en este discurso ilimitado se van borrando progresivamente los legados simbólicos, la alteridad y la imposibilidad que la determina, hasta volverse la vida expresión de un presente absoluto</span>. Sin duda se trata, y los autores lo señalan, de un proceso permanente de “automaximización”. O como lo dicen los propios autores: “el sujeto autoaumentado es el que goza del valor que es él mismo”. O, en otros términos, <span className="sub">el sujeto goza de la producción que aumenta su valor</span>.&nbsp;</p>
<p>En este punto es necesario aclarar e insistir en que “goce” en Lacan es diferente de placer, el que siempre es regulado y limitado. El goce es un “mas allá del Principio del Placer” que se ajusta adecuadamente al dispositivo del rendimiento empresarial vinculado a su carácter compulsivo, adictivo y finalmente su reverso depresivo. Y por supuesto, dado el carácter existencial de estos dispositivos, los mismos afectan a los sectores incluso más desposeídos.</p>
<p>No obstante, a pesar del excelente y completo análisis que Laval y Dardot ofrecen sobre la razón neoliberal no logran explicar por qué esta promesa de volver a la propia vida una empresa interminable de maximización del propio valor resulta tan irresistible y atractiva para los sujetos que se entregan incondicionalmente a la misma, incluso contra sus propios intereses. Tal vez esta cuestión no es despejada con la argumentación suficiente porque los autores incurren en este caso en un error clásico: están atravesados por una noción ambivalente de la categoría del sujeto. Al pensar al sujeto constituido por el Poder, el sometimiento, la sujeción al mismo, se lo presenta como un hecho primario y constitutivo de la existencia humana. Pero el suelo nativo del sujeto, el lugar desde donde adviene a su propia existencia no es el Poder, sino la estructura del lenguaje que lo precede y lo espera antes de su propio nacimiento. El sujeto es un accidente fallido y contingente que emerge en el lenguaje atravesado por la incompletud y la inconsistencia. Radicalmente dividido, agujereado y que necesita siempre de distintos recursos “fantasmáticos“ para soportar su falla constitutiva. Esta es la verdadera razón por la cual la promesa neoliberal puede encontrar su anclaje en el sujeto, e incluso ser deseada. Por ello, es fundamental distinguir metodológicamente al sujeto causado como un efecto contingente por el lenguaje de la “subjetividad” producida por los dispositivos de poder. Si esta distinción no se efectúa el círculo es imposible de cortar. Si la subjetividad esta producida por el poder, ¿por qué razón encontrará en ella misma recursos para sustraerse de aquello que la ha constituido? Como se puede apreciar este es un problema político de primer orden si se desea pensar en experiencias contrahegemónicas con respecto al neoliberalismo.</p>
<p><span className="sub">Nuestra experiencia de lo Común es la copertenencia al surgimiento en la lengua, siempre fallido, en falta y tentado por las diversas promesas imaginarias de &nbsp;“autovalorizarnos” de tal modo que la verdad de nuestra fragilidad constitutiva se esconda para nosotros mismos. He aquí, a nuestro juicio, uno de los secretos que brindan su fuerza a la promesa del imaginario neoliberal</span>.</p>
</div>
<hr></hr>
<div className=" article-info"><div className=" breadcrumb"><div className=" suplement"><a href="https://www.pagina12.com.ar/secciones/el-mundo/notas">El mundo</a></div><div className=" topic"></div></div><div className=" time"><span datetime="2017-08-23" pubdate="pubdate">23 de agosto de 2017</span></div></div>
<div className=" article-titles"><div className=" article-prefix">Opinión</div><div className=" article-title"><h1>La muerte del Amo</h1></div></div>
<div className=" article-body diario"><div className=" article-text"><p>El Amo clásico era aquel capaz de poner en riesgo su vida. Se trataba de su diferencia esencial con el esclavo que protegía su vida a cambio de su libertad.&nbsp;</p>
<p>Pero ahora ha surgido un nuevo Amo en la situación contemporánea de Occidente. No arriesga su vida, la sacrifica en su totalidad inaugurando una nueva figura del crimen y la muerte de carácter serial.</p>
<p>Más allá del entramado geopolítico del asunto y sus complejos y circulares vasos comunicantes, un “ bárbaro” sin otro mandato que matar y morir, ha ganado la escena. No se trata de <span className="sub">la violencia del oprimido descripta por Fanon donde el lumpen se reinventa como sujeto político</span>. No hay proyecto político ni destino emancipatorio alguno, solo se trata de una escalada mortal contra la vida occidental bajo la forma de una play station automática y aniquilante. Se pueden analizar todas las corrientes islámicas que invocan la violencia y combatirlas, se pueden generalizar hipercontroles de diferente eficacia pero no será suficiente. Esta vez existe un “ plus”, una pulsión de muerte absoluta, irreductible de modo definitivo, a una causa histórica exclusiva. ¿Era algo imprevisible o es justamente por ser imprevisible lo que se venia preparando desde hace mucho tiempo? <span className="sub">¿No anticiparon los pensadores de Occidente la figura de un hombre dispuesto a reducir todo a nada?</span></p>
<p>O todo esto será leído retroactivamente como una nueva forma bizarra y transnacional de una “lucha de clases” sin sentido histórico.&nbsp;</p>
<p><span className="sub">¿El nuevo tipo de maldad donde alguien se autodestruye para matar a otro es una invención del Islam o de Occidente?</span></p>
<p>Son preguntas que se formulan en el mismo tiempo histórico donde el Capitalismo engloba todas las acciones humanas</p>
</div></div>
<hr></hr>
<div className=" "><div className=" article-info"><div className=" time"><span datetime="2017-09-29" pubdate="pubdate">29 de septiembre de 2017</span></div></div><div className=" article-titles"><div className=" article-title"><h1>España y Cataluña</h1></div></div><div className=" article-body diario"><div className=" article-text"><p>En tanto exiliado del 76 en España no simpatizo con los nacionalismos. Salvo excepciones, cuando se trata de naciones ocupadas o intervenidas por una potencia extranjera. ¿De qué quieren realmente independizarse los catalanes? <span className="sub">¿Del lastre español que les pesa como un exceso de goce que ellos imaginan que financian? </span>La hegemonía alemana sobre Europa no esta puesta en juego en este tinglado, cuestión esta que la derecha catalana y el sector de la burguesía independentista tiene muy clara.</p>
<p>Pero a su vez, resulta insoportable y falaz que el Estado español y las fuerzas políticas que lo sostienen, que jamás han hecho nada por afrontar con memoria, verdad y justicia todas las consecuencias reales de la dictadura franquista, pretendan ahora una vez más que todo se reabsorba en la legalidad jurídica de un Estado que nunca quiso saber nada del crimen serial franquista.</p>
<p><span className="sub">La historia es el lugar donde lo reprimido reaparece, y nunca de un modo idéntico</span>. Ahora aparece en el independentismo catalán, que a pesar su posible &nbsp;mitología identitaria, encierra esta verdad: que la readaptación del franquismo a las estructuras democráticas de la transición era portadora de un síntoma que de un modo u otro iba a reaparecer.</p>
<p>El aplastamiento del independentismo y la negativa a pactar un referéndum incrementará la fuerza social y conflictiva de este síntoma. El Estado español y la política del Partido Popular y su asociación con el Partido Socialista jamás han construido la legitimidad para afrontar esta situación.&nbsp;</p>
<p>Ni el Estado español con su mantra de la unidad y su permanente referencia al Estado de Derecho, ni la Convergencia, con su inconsistente referencia al derecho de autodeterminación, tienen la legitimidad, no la legalidad, para constituir un proceso constituyente que le dé lugar a una nueva República. Por un lado el Estado español reposa en el asesinato franquista y su encubrimiento del régimen del 78, lo que se &nbsp;puede confirmar con el reverdecer del “nacionalismo español “ en estos días. Por el otro lado la Convergencia, que cogobernó en distinas ocasiones con el Partido Popular, participó de la corrupción y los ajustes procedentes de ese régimen &nbsp;A su vez, ambos participan de los mismos dispositivos neoliberales.</p>
<p><span className="sub">Otra cuestión , y esto es decisivo , es que el significante “Independencia”, dado el estado de movilización popular, se esté vaciando de sentido y se libere del campo semántico al que pertenecía y se vuelva entonces lo que Laclau designa como un “significante en disputa”</span>.</p>
<p>&nbsp;La intromisión represiva del Estado español está logrando que el significante Independencia este virando hacia la cuestión de la Democracia, incluso con posibles alcances instituyentes, que sí pueden llegar a poner &nbsp;en cuestión, tanto el régimen del 78 como la perpetuación neofranquista del Estado español. Es lo que Podemos ha parecido entender, sitúandose en una encrucijada dificilísima que a veces puede aparecer como &nbsp;ambivalente, pero que aloja una coherencia determinante, no sumándose sin más al independentismo pero acompañando la lucha en su posible viraje democrático e instituyente.&nbsp;</p>
</div></div></div>
<hr></hr>
<div className=" article-info"><div className=" breadcrumb"><div className=" suplement"><a href="https://www.pagina12.com.ar/secciones/psicologia/notas">Psicología</a></div><div className=" topic"></div></div><div className=" time"><span datetime="2017-10-12" pubdate="pubdate">12 de octubre de 2017</span></div></div><div className=" article-titles"><div className=" article-title"><h1>El psicoanálisis en el mundo hiperconectado</h1></div></div>
<div className=" article-body diario"><div className=" article-text"><p>Cuando leo a diversos autores que describen con todo rigor las distintas mutaciones “antropológicas” desencadenadas por el <span className="sub">capitalismo digital, financiero, algorítmico e hiperconectado</span>, siempre surge en mí la misma reserva que procede de lo que denomino “izquierda lacaniana. La diferencia irreductible entre el modo de producción de subjetividad propia del capitalismo actual y la invariante estructural del sujeto que adviene en la lengua que se habla y que llega a través del Otro. Decimos la “lengua que se habla” para no confundirla con la elaboración lógica y lingüística que se nombra como lenguaje.</p>
<p>Sean como sean las mutaciones y su posible alcance en el orden antropológico, nunca estamos frente a un nuevo tipo de especie humana. El &nbsp;“embrollo” incurable y fallido por estructura, al que se enfrenta el sujeto en su existencia hablante, sexuada y mortal, siempre retorna. Anudar un cuerpo y sus pulsiones a la palabra y al nombre propio, sobrellevar como se pueda el peso de las identificaciones propias de la inconsistente y pesada novela familiar, la insatisfacción o la imposibilidad del deseo, la voz y la mirada del Otro, etc, siguen marcando de modo inexorable lo que el ser hablante entiende por vida.</p>
<p>He sido uno de los que más he insistido en intentar dar cuenta del modo en que la contemporaneidad incide en estos avatares, pero los mismos no se pueden borrar sin más, en nombre de una permanente mutación antropológica. Las décadas que llevo escuchando al que dice ser, uno por uno, me dejan una constancia definitiva de lo que afirmo.</p>
<p>Por último, en estos teóricos de la megaconexión actual subyace un error político propio de su historicismo antropológico: disolver la constitución del sujeto en una subjetividad que finalmente es idéntica al devenir del Capital. Lo que conduce a un callejón sin salida en el orden político de la cuestión.&nbsp;</p>
<p>Una “izquierda lacaniana” debe dar cuenta con sus recursos teóricos clínicos de ese error de perspectiva.</p>
<p>Las costuras sociopolíticas que saltan por todos lados, en <span className="sub">el mundo del capitalismo de la infoesfera</span> y lo hacen crujir, pueden alcanzar su inteligibilidad si no se borra en la aparición de la nueva subjetividad capitalista aquello que en el sujeto hace objeción a sus mutaciones antropológicas.</p>
</div></div>
<hr></hr>
<div className=" article-info"><div className=" breadcrumb"><div className=" suplement"><a href="https://www.pagina12.com.ar/secciones/contratapa/notas">Contratapa</a></div><div className=" topic"></div></div><div className=" time"><span datetime="2017-11-07" pubdate="pubdate">07 de noviembre de 2017</span></div></div>
<div className=" article-title"><h1>Las rendijas por donde se cuela la historia</h1></div>
<div className=" article-text"><p><span className="sub">El capitalismo en su actual tiempo de concentración se propone subsumir todo en la lógica de sus operaciones megaconectadas</span>. Las distintas narraciones políticas que no acompañen esta marcha incesante e ilimitada cada vez encontrarán más obstáculos para resolver su existencia. Por ello, es habitual ver que a políticos que –en otros tiempos– se los hubiera reconocido de entrada en su nulidad evidente, ahora se les concede a los mismos, una inteligencia especial en sus distintos modos de acumular poder. Hay ciertos intelectuales que tienen un gusto especial por dotar de una agudeza singular a distintos &nbsp;presidentes claramente mediocres, se llamen Mauricio Macri, Mariano Rajoy, etc. En realidad, <span className="sub">es atribuir a los políticos y al sentido que ponen en juego la “astucia” especifica de los dispositivos neoliberales, los cuales sí disponen de un gran capacidad para construir narraciones perfectamente preparadas para la reproducción del poder</span>.</p>
<p><span className="sub">El propósito del neoliberalismo es que los proyectos transformadores y emancipatorios queden relegados a parques temáticos testimoniales o que encarnen una realidad amenazante y caótica. Pero esto varía según las coyunturas</span>.</p>
<p>Si los proyectos emancipatorios quieren llegar a las mayorías, como las mismas están ya intervenidas mediáticamente, es muy difícil que puedan transmitir su discurso. A su vez, si sólo se entregan al cálculo electoral y prescinden de su legado ético y político pierden su filo cortante, su verdad y su razón de ser. En estos casos no que hay más remedio que asumir la apuesta sin garantías, una elección forzada, que revela que la izquierda se define por ser una fuerza, que a diferencia de otras, siempre habita el límite de su propia dispersión, la derecha en este punto siempre se preserva, con su inercia constitutiva, de estas encrucijadas.</p>
<p>En una situación semejante y dado que la partida &nbsp;se juega <span className="sub">en el terreno del Otro neoliberal</span> es muy determinante poder pensar en el acto instituyente, en su lógica discursiva y en el sujeto que fuera capaz de sostenerlo. Ya no habrá insurrección ni corte revolucionario ni ruptura con la realidad constituida. Pero sí rendijas por donde se cuele la historia, la memoria, y aquellos recursos donde un nuevo sujeto se articule a una sensibilidad colectiva distinta al <span className="sub">circuito del desprecio por lo humano propio del neoliberalismo</span>. La articulación de estas sensibilidades que, en determinadas encrucijadas, encuentran un deseo que las relanza a un proyecto, es la tarea mayor de una izquierda que no se deje seducir ni por el parque temático, ni por la tribu testimonial.</p>
</div>
<hr></hr>
<div className=" article-info"><div className=" breadcrumb"><div className=" suplement"><a href="https://www.pagina12.com.ar/secciones/el-pais/notas">El país</a></div><div className=" topic"></div></div><div className=" time"><span datetime="2017-12-04" pubdate="pubdate">04 de diciembre de 2017</span></div></div>
<div className=" article-titles"><div className=" article-prefix">Opinión</div><div className=" article-title"><h1>La sentencia de la ESMA en los medios europeos</h1></div></div>
<div className=" article-body diario"><div className=" article-text"><p><strong>1)</strong> <span className="sub">En el imaginario europeo América Latina es el continente donde el horror es un fenómeno cuasinatural que campea por sus fueros desconectado de las distintas determinaciones internacionales implicadas en el mismo</span>. En muchísimas ocasiones en los 41 años que llevo aquí me han comentado: “Qué cosas terribles han pasado en su país”. Esto en el lugar donde una dictadura asesina permaneció 40 años realizando con una impunidad absoluta todo tipo de crueldades hacia los que resistieron al fascismo. Luego, en el resto de Europa, la Shoa, Mussolini, Salazar, las políticas colonialistas, etc., pertenecen al archivo documental de las horas nocturnas de la TV.</p>
<p><strong>2)</strong> En la sentencia de la ESMA se puso en marcha una maquinaria retórica en concomitancia con lo anterior. “Por fin Argentina juzga los horrores de la dictadura” y distintas variantes moduladas en el mismo sentido. Como si de golpe, bajo el gobierno de Macri, muy reconocible para el oficialismo europeo en sus afinidades políticas, por fin el famoso Estado de Derecho se había hecho cargo de las “víctimas”. <span className="sub">La “víctima” es una de las figuras privilegiadas del orden de dominación neoliberal, siempre que se la presente como descontextualizada del engranaje mundial que la ha promovido</span>.&nbsp;</p>
<p><strong>3)</strong> Por último, una vaga referencia “humanista” a las Madres, siempre bajo el mismo perfil despolitizado. Y por supuesto sin ninguna mención al gobierno anterior, la mancha “populista” que derogó las leyes de Punto Final y de Obediencia Debida, leyes que bajo distintas modalidades siguen vigentes en Europa y especialmente en España.</p>
<p>En muchas ocasiones, he intentado pensar el horror argentino en su singularidad más radical, intentando entrever que cuestiones cruciales de la cultura argentina habían hecho posible el castillo sadiano de los criminales de la dictadura. Pero, en este aspecto, a excepción de algunos &nbsp;intelectuales, escritores, universitarios y políticos, <span className="sub">las poblaciones europeas parecen, ojalá los hechos me lo desmientan, muy contentas de haberse conocido a sí mismas como “demócratas” de toda la vida</span>.</p>
</div></div>
<hr></hr>
<div className="article-info"><div className="breadcrumb"><div className="suplement"><a href="https://www.pagina12.com.ar/secciones/psicologia/notas">Psicología</a></div><div className="topic"></div></div><div className="time"><span datetime="2017-04-20" pubdate="pubdate">20 de abril de 2017</span></div></div>
<div className="article-titles"><div className="article-prefix">El capitalismo actual, Macri y América latina en la visión de Jorge Alemán</div><div className="article-title">“Hay mucho miedo de que se ponga todo mucho peor de como está”</div><div className="article-summary">El reconocido psicoanalista argentino residente en España desde su exilio en los 70 reflexiona sobre el avance neoliberal y los discursos que intenta naturalizar. Psicoanálisis y poder, la izquierda lacaniana en estos tiempos, el valor simbólico de la “revolución de la alegría”.</div></div>
<div className="article-text"><p>El prestigioso psicoanalista y escritor argentino Jorge Alemán se exilió en España en 1976, en plena dictadura argentina, y cuando el país ibérico hacía poco que iniciaba una transición a la democracia, después de casi cuarenta años del régimen dictatorial de Francisco Franco, quien falleció el 20 de noviembre de 1975. Alemán tenía por entonces 25 años. Desde entonces vive en Madrid. Autor de numerosos libros que dan cuenta de un pensamiento que une psicoanálisis, filosofía y política, así como de libros de poesía, durante la segunda mitad de los 70 formó parte de la avanzada del psicoanálisis lacaniano en España y es unos de los intelectuales más consultados. Pero nunca se olvidó de su tierra. Por eso, cuando se le consulta en qué medida el psicoanálisis le ayudó a digerir el dolor del exilio, Alemán expresa: “<span className="sub">El exilio es una experiencia que remite a algo que es constitutivo de cada ser humano: nadie nace en su casa. Todo el mundo nace en el Otro. En cierta forma, siempre hay una parte de uno mismo, así lo señala el psicoanálisis, que es opaca para uno mismo. Uno no es un sujeto autotransparente</span>. De algún modo, el exilio real remite a un exilio más constitutivo, más estructural. Así que a mí me interesó mi propia experiencia analítica para no victimizarme con el exilio, para no sentirlo congelado en las coartadas de la nostalgia o de la melancolía, sabiendo además que yo era una persona que no se quería ir de aquí y que amo intensamente este lugar”. Alemán viajó a la Argentina para dictar hoy y mañana un seminario en la Fundación Centro Psicoanalítico Argentino.</p>
<p><strong>–El psicoanálisis es un teoría que entra en contradicción con los totalitarismos. ¿Cómo puede pensarse, en ese sentido, la relación entre psicoanálisis y poder?</strong></p>
<div className="article-card top-border-black float-left "><div className="card-section"><h5 className="article-prefix">Posdata</h5></div></div><p>–Ahí está la cuestión. El nacimiento del psicoanálisis está marcado por lo que usted señaló. Hay un montón de observaciones de Freud que se pueden leer y volver inteligibles como advertencias sobre el desencadenamiento del totalitarismo: los apuntes de Freud que anticipan el nacionalsocialismo, sus apuntes sobre la Revolución Bolchevique y, en general, la preocupación de Freud por el mal. Hay una línea que continúa esto también en Lacan. Ahora, el problema es que el neoliberalismo ha introducido una nueva logia de poder que es distinta de los regímenes totalitarios que se dieron en el Siglo XX. Por supuesto que los regímenes totalitarios eran antinómicos al psicoanálisis, eran refractarios a éste. Pero el neoliberalismo, a la larga, también lo va a ser porque uno de sus grandes botines de guerra es la subjetividad. Para parafrasear a Marx, <span className="sub">el neoliberalismo es un modo de producción de subjetividad. Y el tipo de subjetividad que promueve y produce no es la del sujeto del inconsciente. Es una subjetividad subordinada a los imperativos de rendimiento, de competencia, de lógicas empresariales, las malditas autoayudas. El sujeto está todo el tiempo confrontado a una exigencia frente a la cual no da la talla y con respecto a la cual siempre está endeudado. Podemos decir que el neoliberalismo es una especie de fábrica, como ya lo han dicho otros teóricos, de deudores y es una mezcla de llamado a la felicidad, una especie de convocatoria a “todos juntos”, “todos felices”, para luego estar en falta con respecto a eso mismo</span>.</p>
<p><strong>–¿Cómo puede pensarse, en ese sentido, la distinción entre sujeto y subjetividad a partir de las teorías de autorrealización y de autoayuda que nacieron bajo el amparo del neoliberalismo?</strong></p>
<p>–Efectivamente creo, como dijo Max Weber, que la Etica Protestante tenía una relación estructural con el capitalismo, <span className="sub">las narraciones de autorrealización, como las de autoayuda, son absolutamente y estructuralmente afines al neoliberalismo. Por lo tanto, la distinción entre subjetividad y sujeto es clave. Es decir: si el neoliberalismo se adueña de todo el orden simbólico y de la propia constitución del sujeto, como lo suelo siempre recordar, se trataría de un crimen perfecto. No habría ninguna forma de establecer ya ningún tipo de resistencia ni de intención política ni de recurso a ningún legado histórico o a una herencia simbólica. Hay que pensar que hay algo en la propia constitución del sujeto, lo que nos vuelve a cada uno de nosotros una existencia mortal, hablante y sexuada, que no puede ser capturada del todo. Si los dispositivos del neoliberalismo capturan esto, entonces, ya no hay nada que hacer</span>.</p>
<p><strong>–¿El neoliberalismo genera patologías específicas?</strong></p>
<p>–Parece ser que hay una que se extiende como una epidemia en el mundo que es la depresión. El aumento de la industria farmacológica de los antidepresivos es un hecho. Y la depresión se puede leer desde dos puntos de vista: uno patológico, pero hay una dimensión ética, como también evocaba Lacan, en&nbsp; donde decía que la depresión era cobardía. No voy a imputar de cobarde a nadie que se deprima, pero es verdad que en la depresión hay una especie de renuncia a las apuestas que los deseos conllevan. En ese sentido, es muy sugerente ver que hay una extensión de ese fenómeno que también me parece muy vinculado <span className="sub">a no dar nunca la talla, a no estar nunca a la altura, a estar siempre arrojados a una situación que nos desborda</span>.</p>
<p><strong>–¿Qué es lo que debería discutir una izquierda lacaniana en estos tiempos?</strong></p>
<p>–Bueno, siempre aclaro lo siguiente: no quiero que los lacanianos se vuelvan de izquierda. No quiero que las escuelas lacanianas sean de izquierda. No quise decir nunca que Lacan era de izquierda. En todo caso, lo caracterizo como un conservador subversivo. Y como un pensador radical, pero no de izquierda. La izquierda lacaniana fue una estrategia teórica que adopté hace años atrás cuando advertí que el recurso al totalitarismo (esa cláusula de reserva de todos los psicoanalistas con respecto a todos los fenómenos colectivos porque <span className="sub">todos los fenómenos colectivos se vuelven totalitarios</span>) había permitido una suerte de escepticismo lúcido con respecto a los fenómenos colectivos o de cinismo inteligente, pero que finalmente era un nuevo tipo de posición de derechas muy afín al neoliberalismo. Una derecha advertida, como diciendo: “Todo esto está muy bien, pero termina fatal” o “Trabajamos en el uno para uno”. Y luego con respecto a lo colectivo, “sólo en aquellos momentos donde hay algo muy grave, muy inquietante, en todo caso podemos decir algo”. Yo creo que la izquierda lacaniana intenta convertirse en una señal de que esto cambió, que ese cinismo y ese escepticismo van en contra del propio psicoanálisis y que éste tiene que abrirse a otro tipo de interpelaciones. Tiene que ser una especie de síntoma en la izquierda. Como lo fue en su origen. Freud y Lacan fueron síntomas para la izquierda.</p>
<p><strong>–¿Qué cree que quiso decir <span className="sub">Lacan cuando expresó: “El inconsciente es la política”</span>?</strong></p>
<p>–Voy a aprovechar una anécdota que me gusta mucho que está en Mi vida, de León Trotsky para ilustrar esto. Lenin le propuso a Trotsky ser ministro de Relaciones Exteriores y Trotsky le dijo: “Estamos en el comienzo de la Revolución, ¿y me vas a nombrar ministro de Relaciones Exteriores que soy judío? Vamos a tener un montón de problemas en Europa, vamos a añadir más problemas a los que ya tenemos”. Lenin le respondió: “Pero, ¿hicimos la revolución para estar pendientes ahora de estos detalles tan estúpidos?”. Trotsky le señaló, entonces: “La Revolución va a terminar con muchas cosas, pero no con la estupidez humana”. Bueno, esto es para mí uno de los sentidos de que <span className="sub">el inconsciente es lo político, que en todo proceso siempre hay elementos que carecen de sentido, repeticiones, cuestiones que quedan fijadas fantasmagóricamente y que es todo un ámbito de la experiencia humana con la que también hay que saber hacer algo políticamente</span>.</p>
<p><strong>–¿Cómo convive en usted esa especie de tensión entre psicoanálisis e izquierda, teniendo en cuenta que uno aborda al sujeto y el otro al colectivo?</strong></p>
<p>–Escribí un libro llamado Soledad: Común para abordar esta tensión. No creo ya en nada donde las piezas encajen. Para mí es un desafío pensar al sujeto en su singularidad, en su soledad radical, en su ser más irrepetible e inconfundible –porque así es la constitución del sujeto–, pero también es muy interesante ver qué es un colectivo. No es tan sencillo definirlo, <span className="sub">salvo que entendamos por colectivo la psicología de las masas o los fenómenos de identificación</span>. No, lo que nos interesa es cuando hay irrupciones igualitarias de lo colectivo, en donde, por un lado, nadie pierde su propia singularidad y, a la vez, está participando en un hecho común. Yo creo que los grandes momentos de la historia fueron de soledad común. Si no todo sería nada más que la historia de los campos de concentración. No creo que hubiera psicología de las masas en el 17 de octubre, en el Mayo del 68, en el 15-M de España o en el Cordobazo. Creo que hay algo donde ahí se reúne lo más singular de cada uno con algo que es, por otro lado, anónimo y colectivo y que se articula algo que puede dar lugar a una invención política.</p>
<p><strong>–¿Cómo puede entenderse en una sociedad con grandes desigualdades la idea de Freud de que la felicidad no tiene que ver con la verdadera existencia del ser humano?</strong></p>
<p>–Esto me parece importantísimo. Una de las razones para ir a un mundo que&nbsp; no sea el capitalista –no sé qué nombre podemos ponerle, podemos ponerle el nombre de comunismo– es para que empiece la verdadera tragedia, es para que surjan las verdaderas diferencias, los locos, los suicidas, porque, en realidad, cuando las diferencias las establece el mercado (dónde nació uno, a qué colegio fue, qué oportunidades tuvo) eso es un insulto a la diferencia, es un modo de encubrirla. Cuando todas las diferencias proceden del lugar donde cada uno tuvo un sitio en el Otro del mercado social, eso no es una diferencia. En realidad, me interesaría mucho la experiencia comunista en la medida en que la veo como una experiencia trágica, donde irrumpirían las verdaderas diferencias no impuestas desde el mercado. No hablo del paraíso en la Tierra, como dice la Internacional.</p>
<p><strong>–<span className="sub">¿Cómo se explica que se puede estar en la miseria y seguir siendo productor de plus de goce?</span></strong></p>
<p>–<span className="sub">Porque es transformación de la miseria. Eso es algo que Marx no contempló. Cuando en El Capital, dice: “La pobreza es la no satisfacción de las necesidades materiales”, desde el concepto de “necesidad” es así. Pero si usted introduce el concepto de goce lacaniano, entonces, hay una mutación de la miseria. En las villas hay armas, plasmas, marcas falsas, drogas de distinto tipo. Hay consumo. La lógica del consumidor consumido se sigue extendiendo. Por supuesto, se consumen los reality, la Play Station, los teléfonos celulares, etcétera</span>.</p>
<p><strong>–¿Cómo analiza la apropiación de la derecha del término “Revolución”? Primero lo había hecho Menem con la “Revolución Productiva”, ahora lo hace Macri con la “Revolución de la Alegría” ¿Qué valor simbólico, en términos lacanianos, le otorgaría?</strong></p>
<p>–Un término que a mis amigos de la izquierda les molesta es cuando digo la palabra “duelo” porque creen que es una cosa psicológica o psicoanalítica cuando, en realidad, yo hablo de un duelo que es un ejercicio activo de trabajo con respecto a esa palabra, tal como la entendíamos en el campo marxista: la ruptura de las relaciones de dominación establecidas por el capitalismo. Yo ahora prefiero la palabra emancipación porque precisamente todo el aparato mediático publicitario hace rato que se ha apropiado de esa palabra. Y además voy a decir algo todavía más grave: <span className="sub">es el propio capitalismo el que es revolucionario. El capitalismo es el que se va a&nbsp; llevar por delante la familia, las instituciones, la relación con el propio lugar. Es el capitalismo el que ha introducido lo ilimitado y no tiene barrera alguna</span>. Entonces, competir con el capitalismo en términos de revolución no me parece muy sensato. Más bien discutiría lo que merece ser conservado. La izquierda lacaniana es conservadora en este punto. O como dicen algunos de Podemos en España: “Somos revolucionarios en lo económico, conservadores con respecto al sujeto y reformistas con respecto a las instituciones”.</p>
<p><strong>–¿Por qué cree, desde la óptica psicoanalítica, que prende el discurso mediático a favor de Mauricio Macri?</strong></p>
<p>–<span className="sub">Hay una apelación permanente a ciertos ideales de distinción o de supuesta diferencia</span>. Todo este asunto del choripán, todo el asunto de desmarcarse del mundo plebeyo, de construir una identidad “abarcadora”. Bueno, todo lo que fue una de las claves del antiperonismo. Hay una cuestión misteriosa en el peronismo muy difícil de explicar fuera de la Argentina. El peronismo no es sólo un modo de construcción política sino un modo de gozar. <span className="sub">Y el goce es uno de los grandes mecanismos del odio. Se odia el goce del otro</span>. Vi un video muy simpático donde un chico pide un choripán y lo insultan de arriba abajo porque odian esa manera de gozar. Ahora, es muy inconsistente eso. No sé cuánto tiempo va a durar Macri con estos recursos imaginarios tan pobres.</p>
<p><strong>–En relación al miedo que se instaura desde el poder hacia abajo, ¿cómo funcionan los mecanismos psíquicos frente al amedrentamiento político?</strong></p>
<p>–Ese es un fenómeno que se da en varios lugares del mundo actualmente. La gente intuye que todo lo que puede venir más adelante puede ser horrible. Ya no hay incertidumbres con respecto al futuro. El futuro puede ser algo parecido a lo que muestran las películas de ciencia ficción: un espectáculo horrible. A su vez, <span className="sub">ya no está esa idea ilustrada de que hay cosas irreversibles. No, cualquier cosa puede ser reversible. Todo puede volver a suceder. Por lo tanto, así como hablábamos antes de la autoayuda en el neoliberalismo, no hay que olvidar su otra cara intimidatoria, su otra cara letal y amenazante en donde el miedo juega un papel importantísimo. Esto es muy importante subrayarlo. Hay mucho miedo de que se ponga todo mucho peor de como está. Y, además, que de hecho puede ocurrir</span>.</p>
<p><strong>–El sector dominante que ahora está en buena parte de los países de América latina no imaginaba que podía darse un proceso democrático progresista como sucedió en la última década. En términos psicoanalíticos, ¿tenían esa idea reprimida?</strong></p>
<p>–Voy a transformar un poco las cosas: fue un retorno de lo reprimido. En los 70, habían sucedido cosas que las derechas históricas creían que habían podido derrotarlas y retornaron. <span className="sub">Si hay algún aspecto que es siempre interesante observar en la historia es el retorno de lo reprimido</span>. En cierta forma es una pasión que da una cierta esperanza porque nunca termina de cerrarse la brecha, siempre puede volver por algún lado. Y lo que ocurrió en la década anterior fue que en América latina volvieron muchas cosas que habían sido esbozadas en los 70. Me diferencio con la izquierda en este aspecto: cuando la izquierda presenta una continuidad absoluta entre el kirchnerismo y el macrismo, el aspecto que me desagrada, como si no hubiera fisuras entre ambos, es que <span className="sub">el kirchnerismo no es hijo de sí mismo</span><span className="com">Ergo: El Macrismo si lo es. Armo un partido de proveta</span>. Hubo muchos exiliados, muchos muertos, costaron muchas vidas ciertos acontecimientos que pudieron suceder bajo el kirchnerismo.</p>
<p><strong>–¿Cómo describiría la autonomía política del psicoanálisis en relación a los 70 en la Argentina?</strong></p>
<p>–Hay que señalar algo muy interesante del psicoanálisis: las rupturas que hubo en los 70, las que hubo en relación a la Asociación Psicoanalítica Internacional fue una ruptura política de psicoanalistas de izquierda. Después, algunos de esos psicoanalistas se dirigieron al peronismo de izquierda. O sea que al final en el psicoanálisis, de un modo u otro, siempre aparece la relación con el mundo político. Ahora mismo, tuvimos un debate reciente con respecto a Venezuela. La Asociación Mundial a la que pertenezco firmó un apoyo de solidaridad con los psicoanalistas que viven en Venezuela y de condena al régimen de Maduro. Yo he manifestado mi diferencia. No porque no tenga constancia de todos los problemas que pueda haber en Venezuela actualmente sino porque me parece que no podemos empezar solamente por Venezuela: hay muchos otros procesos latinoamericanos que merecen también la atención, si los psicoanalistas quieren poner su mirada en el mundo político. Y luego habría que ver cómo fue la génesis en Venezuela. <span className="sub">Yo viví en el Chile de Allende y recuerdo cómo empezó todo el proceso de erosión hasta que Allende se volviera innombrable</span>.</p>
<p><strong>–La última: ¿cree, como psicoanalista, que <span className="sub">la palabra sigue siendo el medio idóneo para avanzar sobre la existencia y la realidad?</span></strong></p>
<p>–Bueno, <span className="sub">incluimos dentro del mundo de la palabra todo lo que puede suceder con las redes, las escrituras, los textos. Y sí, tengo que decirle que sí porque, de nuevo, si le dijera que no, el crimen es perfecto</span>.</p>
<p><em>* Hoy y mañana, a las 19.30, Jorge Alemán brindará el seminario intensivo “El psicoanálisis y el poder. Hacia una izquierda lacaniana” en la Fundación Centro Psicoanalítico Argentino. Panelistas invitados: Mónica Giardina, Alejandro Lezama, Fernando Ramírez y Alfredo García. En Pte. J. E. Uriburu 1345, 1º piso. 4822-4690/4823-4941. <a href="http://fcpa@fcpa.com.ar" title="fcpa@fcpa.com.ar">fcpa@fcpa.com.ar</a></em></p>
</div>
<div className="news-container"><div className="news-header"><div className="news-header-vertical"><div className="news-header-tit-box">

<div className="news-header-pre-tit"><span>ENTREVISTA con christian laval</span></div>

<h1 className="news-header-tit" data-title="&quot;Somos prisioneros del neoliberalismo&quot;">La verdad sobre el neoliberalismo: "La pesadilla que no se acaba nunca... por ahora"</h1>

<h2 className="news-header-opening-txt">¿Se puede aún pensar en el neoliberalismo como aquella ideología que hace del “menos Estado” su característica principal? El último libro de Christian Laval y Pierre Dardot responde a los principales interrogantes sobre el nuevo orden mundial</h2>

</div></div></div>

<div className="news-body" data-scroll-percent="scrollPercent"><div className="news-body-default"><div className="news-body-left"><div className="news-body-info"><div className="news-body-info-box"><span className="news-info-box-title">Autor</span><div className="news-info-box-author"><a href="https://www.elconfidencial.com/autores/miguel-sola-1628/" className="news-def-author" title="Noticias de Miguel Sola" itemprop="author">Miguel Sola</a><div className="news-body-info-box info-box-timeread mrf-hide"><span className="news-info-box-title-timeread">Tiempo de lectura</span><span className="news-info-box-value-timeread">8 min</span></div></div></div></div>



<div className="news-body-center cms-format " id="news-body-center">
<div className="news-body-date"><div className="date-act-block">
<span className="date-act">19.06.2017</span>
 – 
 <span className="date-act-hour">05:00 H.</span>
 </div>
 </div>
 

 <p>El académico francés <strong>Christian Laval</strong>, doctor en Sociología y profesor de la Universidad de París X Nanterre, acaba de publicar junto al filósofo <strong>Pierre Dardot </strong>'<a href="//www.gedisa.com/ficha.aspx?cod=891037&amp;titulo=La-pesadilla-que-no-acaba-nunca#.WUP1xWjyiUk" target="_blank">La pesadilla que no acaba nunca</a>' (Ed. Gedisa). Con ese mal sueño se refieren a la concepción dominante del mundo (hegemónica, si se quiere): el <a href="https://www.elconfidencial.com/tags/otros/neoliberalismo-8432/" target="_blank">neoliberalismo</a>. Sin embargo, no lo ven como cabría esperarse de dos teóricos de la izquierda, como un “mal” de los mercados financieros que tendría como cometido <strong>destruir el espacio público</strong>. Sino, más bien, <span className="sub">como una forma histórica para un nuevo ser humano que, bajo el imperativo del rendimiento y la ley de la <a href="https://www.elconfidencial.com/alma-corazon-vida/2013-08-12/por-que-unos-ganan-siempre-y-otros-pierden-la-ciencia-de-la-competitividad_15939/" target="_blank">competencia</a>, se apropia incluso de la vida más íntima de los individuos</span>.</p>
 <p><b>PREGUNTA. ¿Qué significa esa pesadilla que da título al libro? </b></p>
 <p>RESPUESTA. La gente, nuestros lectores, se preguntan cómo puede ser que no puedan ver el fin del neoliberalismo. Esa es la pesadilla. Es como si fuéramos prisioneros de un sistema del que <strong>parece imposible salir</strong>. Durante sus inicios, el neoliberalismo se presentó como una serie de intentos de nuevas políticas. Por ejemplo, el golpe de Estado en Chile de <a href="https://www.elconfidencial.com/tags/personajes/augusto-pinochet-13730/" target="_blank">Pinochet</a> o la presidencia de <strong>Reagan </strong>en EEUU. Nada parecía presagiar que, en realidad, se trataba de un laboratorio político. Estas experiencias no solo se han manifestado en las políticas económicas, sino que <span className="sub">han creado un sistema (ahora cristalizado) que engloba medidas jurídicas, sociales, educativas, culturales, institucionales… y que ha dado alternativas difícilmente irrealizables</span>.</p>
 <p></p>
 <p></p>
 <p><b>P. ¿Es esa su principal diferencia con <span className="sub">el liberalismo clásico</span>?</b></p>
 <p>R. El clásico, que se constituyó en el siglo XVIII, <span className="sub">tiene como principio el de la limitación del poder político</span>, pues, bajo su concepción, la economía tiene sus propias leyes naturales y por lo tanto no pueden verse interrumpidas por la actividad política o la intervención del gobierno. En este sentido, el neoliberalismo es diferente porque en principio hay una <strong>práctica de la ilimitación</strong>. Es decir, la política de mercado se generaliza en todos los ámbitos de la vida. Denunciar al neoliberalismo como si fuera una renovación de las doctrinas de <a href="https://www.elconfidencial.com/alma-corazon-vida/2012-11-26/10-libros-esenciales-para-entender-en-que-consiste-la-economia_245214/" target="_blank">Adam Smith</a> es equivocarse de época y de objetivo.</p>
 <p><b>P. Usted señala en el libro que este espíritu empresarial, esta competitividad propia del sistema, no solo afecta a las políticas gubernamentales, sino también a lo más íntimo de cada persona. En cierta manera, el 'homo economicus' del neoliberalismo maneja su vida como si se tratase de una empresa. No obstante, ¿por qué es algo tan atractivo para el individuo?</b></p>
 <p>R. El sistema ha creado<strong> nuevas subjetividades</strong>, sí, pero es necesario puntualizar. Interiorizar no significa adherirte a sus principios. El neoliberalismo es, en definitiva, un conjunto de dispositivos que sitúa a la gente en una lógica de competencia sin que se les haya consultado realmente. No es una elección, sino, más bien, una <strong>imposición </strong>que obliga a funcionar dentro de un sistema competitivo. Por ejemplo, es cierto que existe la posibilidad de que las familias elijan una escuela para sus hijos, pero en realidad no es una elección. Se ha impuesto a los padres el deber de elegir y optar por una u otra escuela. Es decir, se les ha empujado a formar parte del juego. Estas formas de naturalización de la competitividad son difíciles de detectar. Por un lado, hay gente que lo ha asumido de forma natural, pero por otro hay muchos que no son conscientes de haber caído en esta espiral.</p>
 <p><b>P. </b><b>Pueden ser conscientes o no, pero un sistema que abarca tanto afectará a todos por igual.</b></p>
 <p>R. Por un lado, genera <strong>nuevas patologías</strong> como el estrés, la ansiedad o las depresiones. Esta competitividad empuja a la gente a sus propios límites. Es la misma lógica del capital, hacer cada vez más. Se interioriza y <strong>empuja al individuo a ir siempre más allá</strong>, igual que en el deporte de élite. Y por otro, si observamos la colectividad, también vemos una dificultad para reaccionar conjuntamente. La acción colectiva necesaria para cambiar las reglas brilla por su ausencia. El sistema se cristaliza. Si en la URSS se contestaba con represión, el neoliberalismo hace lo propio con la inhibición de la acción colectiva.</p>
 <p><span className="summary block-summary quote-on">En el neoliberalismo, la política de mercado se aplica a todos los ámbitos vitales</span></p>
 <p><b>P. ¿Y por qué esta competitividad en todos los aspectos de la vida puede ser una amenaza para la propia democracia? </b></p>
 <p>R. En el campo político observamos que esta competitividad se ha convertido en el principio institucional, superior a la voluntad de los ciudadanos. Las leyes, las reformas del mercado de trabajo, bajar los impuestos a las grandes empresas... Todo esto se produce en nombre de la competencia internacional. Destruimos todos los dispositivos sociales que se han puesto en marcha en nombre de esta competitividad. Esto <strong>se ha convertido en un principio superior</strong>, incluso supremo, en relación con la elección, las necesidades y los derechos fundamentales de los ciudadanos, como por ejemplo la educación o la seguridad. Asimismo, el hecho de que los partidos de izquierda y derecha, en el fondo, terminan apoyado las mismas políticas de competitividad ha supuesto una verdadera destrucción del debate, el diálogo e incluso de la diferencia política. Como consecuencia, los electores <strong>dejan de confiar en los partidos</strong>.</p>
 <p><b>P. En este contexto, ¿la crisis de 2008 es un mero error pasajero del sistema o más bien una estrategia creada para que el neoliberalismo expanda su influencia y poder?</b></p>
 <p>R. La activista <a href="https://www.elconfidencial.com/alma-corazon-vida/2015-03-27/cualquiera-que-critique-hoy-al-capitalismo-es-considerado-como-un-radical-peligroso_736624/" target="_blank">Naomi Klein</a> habla de que la <strong>crisis</strong> ha sido creada expresamente para imponer este modelo. Nosotros, en cambio, consideramos que la crisis es una parte o defecto implícito, uno más, de la lógica neoliberal. Lo que está claro es que sus políticas se apoyan en la misma para reforzar más el espíritu empresarial.</p>
 <p><span className="summary block-summary quote-on">Hemos destruido los dispositivos sociales en nombre de la competencia internacional</span></p>
 <p><b>P. </b><b>Por un lado hablan de esa mayoría que no tiene alternativas, que cada vez vive peor. </b><b>En el otro, estarán los que se benefician. </b><b>¿Quién forma parte de esa élite a la que le conviene el neoliberalismo?</b></p>
 <p>R. El movimiento Occupy Wall Street hablaba del 1% contra el 99%, nosotros del <strong>bloque oligárquico neoliberal</strong>. Los que se benefician son una pluralidad de personas interconectadas e interdependientes que refuerzan y perpetúan el sistema. Los identificamos en cuatro grupos principales: la burguesía en el sentido más clásico, una élite política y administrativa, otra mediática y por último una élite de intelectuales, sobre todo (pero no solo) los economistas. Estos grupos se caracterizan por ser defensores y beneficiarios del sistema.</p>
 <p><b>P. Un editorial del 'Financial Times' aseguraba que “cualquier ataque contra el sistema neoliberal le da aire a los regímenes opresivos”. Esta advertencia se enmarca durante el auge de la xenofobia, los nacionalismos, el Frente Nacional, movimientos identitarios… ¿Tienen algo que ver? ¿Criticar al sistema es jugar con fuego?</b></p>
 <p>R. Me alegra de que el mismo periódico que reproduce el sistema neoliberal, en este caso el 'Financial Times', se haya preocupado por la situación en la que nos encontramos. La competitividad generalizada se manifiesta en los salarios, las leyes y, en definitiva, en todos los aspectos de la vida cotidiana. Esto tiene una <strong>reacción </strong>clara: la protección de la sociedad de los débiles y de aquellos que se consideran víctimas. Y sí, esta respuesta ha tenido como contrapartida la emergencia de nacionalismos, movimientos de soberanía, el Brexit, Trump… Como se puede ver, en los países en los que se inició el sistema, las reacciones han sido más fuertes. En cualquier caso, el 'FT' se olvida del otro punto de resistencia: <a href="https://www.elconfidencial.com/tags/personajes/jean-luc-melenchon-19448/" target="_blank">Mélenchon</a> en Francia, <strong>Corbyn </strong>en Reino Unido, <a href="https://www.elconfidencial.com/tags/personajes/bernie-sanders-17075/" target="_blank">Bernie Sanders</a> en EEUU… Hay, por tanto, dos reacciones opuestas, en las antípodas, ante la dictadura de la competitividad.</p>
 <p><span className="summary block-summary quote-on">La acción colectiva necesaria para cambiar las reglas del sistema brilla por su ausencia</span></p>
 <p><b>P. </b><b>Si el neoliberalismo es la pesadilla que no acaba nunca, </b><b>¿no estarán </b><b>estas respuestas condenadas al fracaso?</b></p>
 <p>R. La pesadilla que no se acaba nunca… por ahora. Es verdad, todavía no no hemos despertado. Pero hay que tener en cuenta que este nuevo libro lo situamos después de '<a href="http://gedisa.com/ficha.aspx?cod=891029&amp;titulo=Com%C3%BAn#.WUP4yGjyiUk" target="_blank">Común: ensayos sobre al revolución en el siglo XX</a>'. Si ponemos en relación los dos textos, el lector verá que aunque vivamos en una pesadilla, se está produciendo un cambio, que estamos en un época para reinventar alternativas, experimentar con políticas y movimientos sociales. Somos testigos de la creación de un nuevo discurso, un nuevo léxico. Todo esto contesta al sistema neoliberal sobre la base de una nueva izquierda. El mensaje que procuramos transmitir es, por tanto, <strong>optimista</strong>. No es una profecía. Pero insistimos en que hay que analizar estos cambios esperanzadores que se están produciendo.</p>
 <p><b>P. Podemos ha dejado atrás el “ni de izquierdas ni de derechas” y ha acabado ocupando su lugar como partido de izquierda en el Parlamento. ¿Considera que ellos son parte de esa solución (de lo común) que usted espera?</b></p>
 <p>R. Lo relevante del caso de Podemos es el vínculo histórico entre un <strong>movimiento social</strong> y un partido que por supuesto no puede tener el monopolio de la expresión de todo el pueblo. El error sería que el mismo partido impidiera los intentos de nuevas propuestas y alternativas, como con <a href="https://www.elconfidencial.com/tags/personajes/inigo-errejon-13175/" target="_blank">Iñigo Errejón</a>. El riesgo es que se podría caer de nuevo en los peligros del vacío dirigente. La figura del partido comunista está completamente superada. La pregunta realmente interesante es <strong>cómo puede seguir siendo un partido joven</strong>, que evite que los dirigentes lo sean durante toda la vida, que se conviertan en profesionales. Dicho esto, merece la pena resaltar que cada partido busca su nuevo estilo y que no es seguro que lo consigan al primer intento.</p>
 </div></div></div></div>

</div>
  </div>
    </div>
    );
}