import xs, { Stream } from 'xstream';
import { VNode } from '@cycle/dom';

export function Hall(sources: {}) {

  const hall: Stream<VNode>[] = [];

  return {
    DOM: view(hall)
  };
}

function view(doms: Stream<VNode>[]) {
  return xs.combine(...doms)
    .map(hall =>
      <div className='pure-g'>
      <style jsx>{`
      	        .img {
    width: 90%;
    }
p, ul, ol {font-size: 120%; color: #8D4A13;}.sub {color: #190D54; background:#DDD6FE} .no {color: #252527; background:#EDDCDC} .subGreen {color: #186A26; background:#BCE9C2}.subOr {color: #A17413; background:#ffeaea} .humor {color: #903211; background:#ffeaea} .coment {font-size:90%; font-weight: bold; font-style: italic; color: #0F4747;} blockquote .sum{font-size: 100%; font-weight: bold; color: #F7F6F9;background-color: lightblue; padding: 10px; border: 1px solid #4CAF50;} .pag {font-size: 70%;color: #2C9494; }
.sum{background-color: lightblue; padding: 10px;} aside {font-size: 15px; display: block; padding: 10px; border: 1px solid #4CAF50; padding-left:50px} .item-aside { width: 4 / 12 * 100%; position: absolute; z-index: -1; top: 0; right: 0; padding-left: 10px * 2 + 1px; padding-right: 10px; opacity:0;transition: all 400ms; // left line &::after { content: '';position: absolute; top: 0; bottom: 0; left: 10px; border-left: 1px #ddd solid; } &:hover { z-index: 1; opacity: 1; }}`}</style>
        <div className='pure-u-1-1'>
<h1>Stuart Hall</h1>
<h2>Codificar y Decodificar</h2>
<h3>En: CULTURE, MEDIA Y LENGUAJE, London,
Hutchinson, 1980. Pág. 129-139 </h3>
<h4>Traducción: Silvia Delfino</h4>
<span>Producción - Circulación - Distribucion - Consumo - Reproduccion</span>
<span>Lecturas: Dominante - Negociada y Oposicional</span> 
<p>Tradicionalmente, la investigación en comunicación de masas ha conceptualizado el proceso de comunicación en términos de circuito de circulación. Este modelo ha sido criticado por su linealidad <strong>-Emisor/Mensaje/Receptor-</strong> por su concentración en el nivel del intercambio de mensaje y por la ausencia de una concepción estructurada de los diferentes momentos como una estructura compleja de relaciones. Pero también es posible &#40;y útil&#41; pensar este proceso en términos de una estructura producida y sostenida a través de la articulación de momentos relacionados pero distintivos <strong>-Producción, Circulación, Distribución/Consumo, Reproducción-</strong>. <span className="sub">Como funciona en tiempos de internet, buscar en Hito Steyerl</span> Esto llevaría a pensar el proceso como una estructura compleja dominante”, sostenida a través de la articulación de prácticas conectadas, cada una de las cuales, retiene sin embargo, su carácter distintivo y tiene su modalidad específica propia, sus propias formas y condiciones de existencia. Esta segunda aproximación, homóloga a la que forma el esqueleto de la producción material ofrecida
en los "Manuscritos" y "El Capital" de Marx, tiene además la ventaja de descubrir más agudamente cómo un circuito continuo <strong>-producción- distribución-producción-</strong> puede sostenerse a través del “pasaje de formas”. También ilumina la especificidad de las formas en que el producto del proceso “aparece” en cada momento, y de ese modo, qué distingue “producción” discursiva de otros tipos de producción en nuestra sociedad y en los sistemas de comunicación modernos.</p>
<p>El “objeto” de estas prácticas es el significado y los mensajes en la forma de vehículos de signos de una clase específica organizados, como cualquier forma de comunicación o lenguaje, a través de las operaciones de códigos dentro de la cadena sintagmática<sub>1</sub> de un discurso. Los aparatos, relaciones y prácticas de producción así concebidas, en un cierto momento &#40;el momento de producción/circulación&#41; en la forma de vehículos simbólicos construidos dentro de las reglas del “lenguaje”. Este proceso requiere, de este modo, en el fin de la producción, sus instrumentos materiales -sus “medios”- así como sus propios equipos de relaciones sociales &#40;de producción&#41;- la organización y combinación de prácticas dentro de los aparatos de los medios masivos de comunicación, pero es en la forma discursiva que la circulación del producto tiene lugar, así como su distribución a las distintas audiencias. <span className="sub">Una vez completado, el discurso debe entonces ser traducido-transformado nuevamente en prácticas sociales si el circuito va a ser a la vez completado. Si no hay “significado” puede no haber “consumo”. Si no se articula el significado en la práctica, no tiene efecto</span><span className="com">Guau!!!</span>. El valor de esta aproximación es que mientras cada uno de los momentos, en articulación, es necesario para el circuito como un todo, ningún momento puede garantizar completamente el momento siguiente con que está articulado. Desde que cada momento tiene su modalidad específica y sus condiciones de existencia cada una puede constituir su propio corte o interrupción del “pasaje de formas” de cuya continuidad depende el fluir de producción efectiva &#40;esto es, reproducción&#41;.</p> 
<p>Así, no queriendo limitar la investigación “a seguir sólo aquellas líneas guías que emergen de los análisis de contenido”, debemos reconocer que la forma discursiva del mensaje tiene una posición privilegiada en el intercambio comunicativo &#40;desde el punto de vista de la circulación&#41;, y que <span className="sub">los momentos de “codificación” y “decodificación” son momentos determinados, a través de una “autonomía relativa” en relación con el proceso de comunicación como un todo</span>. Un hecho histórico no puede, de este modo, ser transmitido “en bruto” en, por ejemplo, un noticiero televisivo. Los hechos pueden ser significados sólo dentro de las formas</p> 
<center>Página 1</center>
<p>auditivo-visuales del discurso televisivo. <span className="sub">En el momento en que un hecho histórico pasa bajo el signo del discurso, está sujeto a todas las “reglas” complejas formales a través de las cuales el lenguaje significa</span>. Para decirlo en forma paradójica, <span className="sub">el evento debe convertirse en una “historia/relato” antes de que pueda convertirse en un evento comunicativo</span>. En ese momento las sub-reglas formales del discurso están “en función dominante”, sin, por supuesto subordinar la existencia del evento histórico así significado, las relaciones sociales en las cuales las reglas trabajan o las consecuencias sociales o políticas del evento que ha sido significado de este modo. <span className="sub">La “forma mensaje” es la “forma de aparición” necesaria del evento en este pasaje entre la fuente y el receptor</span>. De este modo la transposición dentro y fuera de la “forma mensaje” &#40;el modo de intercambio simbólico&#41; no es un momento “azaroso” que podamos olvidar o ignorar de acuerdo con nuestra conveniencia. La “forma mensaje” es un momento determinado, aunque, a otro nivel, comprende los movimientos superficiales del sistema de comunicaciones y requiere, en otro nivel, ser integrado dentro de las relaciones sociales del proceso de comunicación como un todo, del cual el sólo forma parte.</p> 
<p>Desde esta perspectiva general, podemos caracterizar el proceso de comunicación televisivo, grosso modo, como sigue. Las estructuras institucionales de broadcasting, con sus prácticas y redes de producción, sus relaciones organizadas o infraestructuras técnicas, se requieren para producir un programa. Usando la analogía de "El Capital" éste es el “proceso de trabajo” en el modo discursivo. La producción aquí, constituye el mensaje. En un sentido, entonces el circuito comienza aquí. Por supuesto, el proceso de producción no carece de su aspecto “discursivo”: éste también está estructurado a través de significados e ideas conocimiento en uso acerca de las rutinas de producción, desempeños técnicos históricamente definidos, ideologías profesionales, conocimiento institucional, definiciones y creencias, creencias acerca de la audiencia, etc., la estructura o marco de constitución del programa a través de su estructura de producción. Más aún, aunque las estructuras de producción de televisión originan el discurso televisivo, ellas no constituyen un sistema cerrado. Ellas reúnen temas, tratamientos, agendas, eventos, personas, imágenes de audiencia, “definiciones de situación” de otras fuentes y otras formaciones discursivas dentro de estructuras políticas y socio-culturales más amplias, de las cuales son sólo una parte diferenciada. Philip Elliot expresó esto suscintamente, dentro de un marco de trabajo más tradicional, en su discusión sobre el modo en que la audiencia es a la vez “origen” y “receptor” del mensaje televisivo. Así, tomando prestados términos de Marx -circulación y recepción son, en efecto, “momentos” del proceso de producción en televisión y son incorporados mediante un número de retroalimentaciones estructuradas e indirectas, en el proceso mismo de producción.</p>
<p>El consumo y recepción del mensaje televisivo es también él mismo un “momento” del proceso de producción en un sentido más amplio, a pesar de ser el último en “predominante” porque es el “punto de partida de la efectivización” del mensaje. La producción y recepción del mensaje televisivo no son, por lo tanto, idénticas pero están relacionadas: son momentos diferenciados dentro de la totalidad formada por las relaciones sociales del proceso comunicativo como un todo.</p> 
<p>En cierto punto, sin embargo, las estructuras de radiofonía deben ofrecer mensajes codificados en la forma de discurso significativo. Las relaciones institucionales y sociales de producción deben pasar por las reglas discursivas del lenguaje para que su producto se haga efectivo. Esto inicia un momento diferenciado posterior, en el cual las reglas formales del discurso y de lenguaje están en función dominante. Antes de que este mensaje pueda tener un “efecto”, satisfacer una “necesidad” o ser puesto en “uso” debe primero ser apropiado en tanto discurso significativo y estar significativamente codificado. Es este conjunto de significados codificados el que “tiene un efecto”, influye, entretiene, instruye o persuade, con consecuencias de comportamiento, perceptuales, cognitivas, emocionales, ideológicas muy complejas. En un momento “determinando” el “mensaje” a través de su decodificación se emite dentro de la estructura de las prácticas sociales. Estamos completamente advertidos de que esta re-entrada</p> 
<center>Página 2</center>
 <p>en las prácticas de recepción de audiencia y “uso” no puede ser entendida en términos simples de conductismo. Los procesos típicos identificados en la investigación positivista como elementos aislados -efectos, usos, “gratificación”-, están ellos mismos encuadrados en estructuras de entendimiento, a la vez que son producidos por relaciones sociales y económicas que modelan su “efectivización” en la recepción al final de la cadena y que permitan que los contenidos significados en el discurso sean transpuestos en práctica o conciencia &#40;para adquirir valor de uso social o efectividad política&#41;.</p>
 <img src={'/screens/esquema.jpg'} alt="esquema" className="img"/> 
 
 <p>Obviamente lo que hemos etiquetado en el diagrama como “estructuras significativas 1” y “estructuras significativas 2” pueden no ser las mismas. No constituyen una “inmediata identidad”. Los códigos de codificación y decodificación pueden no ser perfectamente simétricos. Los grados de simetría -esto es, los grados de “comprensión” o “incomprensión” en el intercambio comunicativo-depende de los grados de simetría/asimetría (relaciones de equivalencia) establecidos entre las posiciones de “ personificaciones”, codificador- productor y decodificador-receptor. Pero esto a su vez depende de los grados de identidad - no identidad entre los códigos que perfecta o imperfectamente transmiten, interrumpen o sistemáticamente distorcionan lo que tiene que ser transmitido. La ausencia de ajuste entre los códigos tiene mucho que ver con las diferencias estructurales de relación y posición entre los emisores radiales y las audiencias, pero también tiene algo que ver con la asimetría entre los códigos de la “fuente” y el “receptor” en el momento de transformación dentro y fuera de la forma discursiva. Lo que se llama “distorsiones” o “malentendidos” surge precisamente por la falta de equivalencia entre dos lados del intercambio comunicativo. Una vez más, esto define la “autonomía relativa” pero “determinación” de la entrada y salida del mensaje en sus momentos discursivos.</p>
<p>La aplicación de este paradigma rudimentario ha comenzado a transformar ya nuestra comprensión del viejo término, “contenido” televisivo. Estamos comenzando a ver cómo puede también transformar nuestra comprensión de la recepción de la audiencia, “lectura” y respuesta. Los comienzos y los finales ya han sido anunciados antes en la investigación de comunicaciones, por lo tanto debemos ser cuidadosos. Pero parece haber base para pensar que se está abriendo una faz nueva y excitante en la llamada investigación de audiencia, pero de un nuevo tipo. En cualquiera de los extremos de la cadena comunicativa el uso del paradigma semiótico promete disipar el behaviorismo que ha entorpecido la investigación en medios masivos por tanto tiempo, especialmente en esta aproximación al contenido. Aunque sepamos</p> 
<center>Página 3</center> 
<p>que el programa de televisión no es un input de conducta, ha sido casi imposible para los investigadores tradicionales conceptualizar el proceso comunicativo sin patinar en una u otra variante del behaviorismo de corto vuelo. Sabemos como Gerbner ha indicado que las representaciones de violencia en la pantalla de televisión “no son violencia sino mensajes acerca de violencia” pero hemos continuado investigando la cuestión de la violencia, por ejemplo, como si fuéramos incapaces de comprender la distinción epistemológica.</p>
<p>El signo televisivo es complejo. Está constituido por la combinación de dos tipos de discurso, visual y auditivo. Más aún, es un signo icónico, en la terminología de Pierce, porque “posee algunas de las propiedades de la cosa representada”. Este es un punto que ha conducido a grandes confusiones y ha instalado una intensa controversia en el estudio del lenguaje visual. En la medida en que el discurso visual traspone un mundo tridimensional a planos bidimensionales, no puede, por supuesto ser el referente o concepto que significa. Un perro en una película puede ladrar pero no puede morder. La realidad existe fuera del lenguaje pero está constantemente mediada por y a través del lenguaje en relaciones y condiciones reales. Así no existe un discurso inteligible sin la operación de un código icónico y los signos son por lo tanto signos codificados también -aún si los códigos funcionan en forma muy diferente aquí en los de otros signos. No hay grado cero en el lenguaje. En el naturalismo y “realismo” la aparente fidelidad de la representación de la cosa o del concepto representado, es el resultado, el efecto de una específica articulación del lenguaje sobre lo “real”. Es el resultado de una práctica discursiva.</p> 
<p>Ciertos códigos pueden, por supuesto, estar tan ampliamente distribuidos en el lenguaje específico de una comunidad o cultura, y haber sido aprendidos a tan temprana edad, que puede parecer que no están construidos -el efecto de una articulación entre signo y referente- sino ser dados “naturalmente”. Los signos visuales simples parecen haber adquirido una “casi- universalidad” en este sentido: aunque reste evidencia de que son aparentemente códigos visuales “naturales” son específicos de una cultura. Sin embargo, esto no significa que no existan códigos que han sido profundamente “naturalizados”. La operación de códigos naturalizados revela no la transparencia y “naturalidad” del lenguaje sino la profundidad del hábito y la “casi- universalidad” de los códigos en uso. Ellos producen reconocimientos aparentemente “naturales”. Esto tiene el efecto &#40;ideológico&#41; de ocultar las prácticas de codificación que están presentes. Pero no debemos ser engañados por las apariencias. En realidad lo que el código naturalizado demuestra es el grado de hábito producido cuando hay un vínculo y reciprocidad -una equivalencia- entre los extremos de codificación en un intercambio de significados. El funcionamiento de los códigos en el extremo de la decodificación frecuentemente asumirá el status de percepciones naturalizadas. Esto conduce a pensar que el signo visual de “vaca” en realidad es &#40;más que representa&#41; el animal, vaca. Pero ni pensamos en la representación visual de una vaca en un manual y más aún en el signo lingüístico “vaca” - podemos ver que ambos, en diferentes grados son arbitrarios con respecto al concepto de animal que ellos representan. La articulación de un signo arbitrario -ya sea visual o verbal- con el concepto de un referente es el producto, no de la naturaleza sino de la convención, y la convención de los discursos requiere la intervención, el soporte, de códigos. Así Eco sostiene que los signos icónicos “lucen como los objetos en el mundo real porque reproducen las condiciones &#40;esto es, los códigos&#41; de percepción en el sujeto que los ve”. Estas “condiciones de percepción” son, sin embargo, el resultado de una alta codificación, &#40;aún si son virtualmente inconscientes&#41; de un conjunto de operaciones de decodificación. Esto es tan cierto con respecto a la imagen fotográfica o televisiva como lo es de cualquier otro signo. Los signos icónicos son, sin embargo particularmente vulnerables de ser leídos como naturales porque los códigos de percepción visual están ampliamente distribuidos y porqué este tipo de signo es menos arbitrario que el lingüístico: el signo lingüístico “vaca” no posee ninguna de las propiedades de la cosa representada, mientras que el signo visual parece poseer algunas de estas propiedades.</p> 
<center>Página 4</center> 
<p>Esto puede ayudarnos a clarificar la confusión en la teoría lingüística y a definir con precisión algunos términos claves que se utilizan en este artículo</p>
<p>La teoría lingüística frecuentemente emplea la distinción entre “denotación” y “connotación”. El término “denotación” se equipara con el sentido literal de un signo. “Connotación” en cambio suele ser empleado simplemente para referirse a significados menos fijados y por lo tanto más convencionalizados, asociativos, los cuales varían y dependen de la intervención de códigos.</p>
<p>Nosotros no usamos la distinción denotación/connotación en este sentido. Desde nuestro punto de vista se trata de una distinción analítica que no debe ser confundida con distinciones en el mundo real. Hay muy pocas instancias en que los signos organizados en un discurso signifiquen sólo su sentido “literal” &#40;es decir, un consenso casi universal&#41;.</p> <p>En el discurso real la mayoría de los signos combinan ambos aspectos, el denotativo y el connotativo. Se puede preguntar entonces si es útil mantener esta distinción. El valor analítico reside en que el signo parece adquirir su valor ideológico pleno -parece estar abierto a la articulación con discursos y significados ideológicos más amplios- en el nivel de los significados “asociativos” &#40;esto es, en el nivel connotativo&#41; -porque los significados no están fijados en una natural percepción &#40;no están naturalizados&#41; y su fluidez de significado y asociación puede ser más ampliamente explotada y transformada. Por lo tanto, es en el nivel connotativo del signo que las situaciones ideológicas alteran y transforman la significación. En este nivel podemos ver más claramente la intervención de las ideologías en y sobre el discurso: aquí el signo se abre a nuevos acentos, entonaciones y, en términos de Voloshinov, entra plenamente en una lucha acerca de las significaciones, la lucha de clases dentro del enunciado. Esto no significa que el significado denotativo o “literal” está fuertemente fijado porque se ha vuelto tan plenamente universal y “natural”. Los términos “denotación” y “connotación” entonces son herramientas analíticas, no para distinguir en contextos particulares, entre la presencia/ausencia de ideología en el lenguaje sino para distinguir los diferentes niveles en los cuales ideologías y discursos se interceptan.</p> 
<p>El nivel de la connotación en el signo visual, de su referencia contextual y posición en los diferentes campos discursivos de significación y asociación, es el punto donde los signos ya codificados se intersectan con los códigos semánticos profundos de una cultura y toman una dimensión ideológica adicional, más activa. Podemos tomar un ejemplo del discurso publicitario. Aquí tampoco existe lo puramente denotativo y ciertamente no hay representación “natural”. Todo signo visual en publicidad connota una cualidad, situación, valor o inferencia, que está presente como un significado de implicancia o implicación que depende de su posición connotacional. En el ejemplo de Barthes, el sweater siempre significa “abrigo cálido” &#40;denotación&#41; y de allí la actividad/valor de “conservar el calor”. Pero en sus niveles más connotativos también puede significar “la llegada del invierno” o “un día frío”. Y en sub-códigos de la moda especializados sweater puede significar muy diversas cosas.</p> 
<p>En este nivel claramente se contrae relaciones del signo con un universo de ideologías en la sociedad. Estos códigos son los medios por los cuales el poder y la ideología significan en los discursos particulares. Ellos remiten los signos a los “mapas de significados” en los cuales cualquier cultura está clasificada; y estos “mapas de realidad social” tienen un amplio espectro de significados sociales, prácticas, usos, poder e intereses “escritos” en ellos. Los niveles connotativos de significación como resalta Barthes, “tienen una estrecha comunicación con la cultura, el conocimiento, la historia, y es a través de ellos que el contexto, entorno del mundo invade el sistema lingüístico y semántico. Ellos son, fragmentos de ideología” &#40;Barthes R: Elementos de semiología&#41;.</p> 
<p>El sí llamado nivel denotativo del signo televisivo está fijado por ciertos códigos muy complejos pero limitados o “cerrados”. Su nivel connotativo, aunque también está limitado, es más abierto, sujeto a transformaciones más activas, que explotan sus valores polisémicos. Cualquier signo ya constituido es potencialmente transformable en una configuración</p>
<center>Página 5</center> 
<p>connotativa &#40;o varias&#41;. La polisemia no debe ser confundida sin embargo con el pluralismo. Los códigos connotativos no son iguales entre ellos. <span className="sub">Cualquier sociedad o cultura tiende, con diferentes grados de clausura, a imponer sus clasificaciones del mundo político, social y cultural. Estas constituyen el ORDEN CULTURAL DOMINANTE aunque nunca sea unívoco o no contestado</span>. La cuestión de la “estructura de discursos dominantes” es un punto crucial. Las diferentes áreas de la vida social están diseñadas a través de dominios discursivos jerárquicamente organizados en significados dominantes o preferentes. Los eventos nuevos, problemáticos o conflictivos que quiebran nuestras expectativas o nuestras construcciones de sentido común, deben ser asignados a sus dominios discursivos antes de que puedan “tener sentido”. El modo más común de ubicar en el “mapa” estos hechos es asignar lo nuevo a algún dominio de los existentes en el “mapa de la realidad social problemática”. Decimos “dominantes” y no  determinantes” porque siempre es posible ordenar, clasificar y decodificar un evento dentro de más de uno de los dominios. Pero decimos “dominante” porque existe un patrón de “lecturas preferentes” y ambos llevan el orden institucional/político e ideológico impreso en ellos y se han vuelto ellos mismos institucionalizados. Los dominios de los significados “preferentes” están embebidos y contienen el sistema social como un conjunto de significados, prácticas y creencias: el conocimiento cotidiano de las estructuras sociales, de “cómo funcionan las cosas para todos los propósitos prácticos en esta cultura”, el rango de poder e interés y la estructura de limitaciones y sanciones. Entonces para clarificar un “malentendido” en el nivel connotativo, debemos hacer referencia, a través de los códigos, a los órdenes de la vida social, del poder económico y político. Más aún, en tanto estos campos están estructurados en “dominantes” pero no cerrados, el proceso comunicativo, consiste no en una asignación aproblemática de cada item visual a su posición dada dentro de un conjunto de códigos pre-asignados, sino que consiste en reglas performativas -reglas de competencia y uso, de lógicas -en uso- que buscan activamente reforzar o proferir algún dominio semántico sobre otro del mismo modo que items o normas dentro y fuera de sus conjuntos apropiados de significaciones. La semiología formal ha descuidado a menudo esta práctica de trabajo interpretativo aunque constituya de hecho, las relaciones reales de transmisión de prácticas en televisión.</p> 
<p>Al hablar de significaciones dominantes, entonces, no estamos hablando de un lado del proceso que gobierna cómo los hechos serán significados. Consiste en el “trabajo” necesario para reforzar, ganar plausibilidad y dirigir como legítima la decodificación de un evento dentro del límite de definiciones dominantes en las cuales ha sido connotativamente significado. <span className="sub">Terni ha resaltado: “con la palabra lectura no queremos decir sólo la capacidad de identificar y descodificar un cierto número de signos, sino también la capacidad subjetiva de ponerlos en una relación creativa entre ellos y otros signos: una capacidad que es, por sí misma, la condición para una conciencia completa del entorno total de cada uno” &#40;“Entendiendo la Televisión”&#41;</span>.</p> <p>Nuestra discusión aquí es con la noción de “capacidad subjetiva”, como si el referente de un discurso televisivo fuera un hecho objetivo pero el nivel interpretativo fuera un asunto individualizado y privado. El caso parece ser el opuesto. La práctica televisiva toma la responsabilidad “objetiva” &#40;esto es, sistemática&#41; precisamente por las relaciones que vinculan los signos con otros en cualquier instancia discursiva, y así, continuamente reacomoda, delimita y prescribe dentro de qué “conciencia del entorno total de uno” se incluyen estos items.</p> 
<p>Esto nos lleva al problema de los “malentendidos”. Los productores de televisión que encuentran que sus mensajes “fracasan en ser comunicados” están frecuentemente preocupados por ordenarnos, alisar los pliegues en la cadena de comunicación. La mayoría de las investigaciones que reclaman la objetividad de un “análisis de planificación” reproduce el objetivo administrativo tratando de descubrir en qué medida la audiencia reconoce un mensaje y de incrementar el grado de comprensión. Sin duda existen malentendidos de tipo literal. Si un televidente no conoce los términos empleados, no puede seguir la lógica compleja del</p> 
<center>Página 6</center>
<p>argumento o la exposición, por no estar familiarizado con el lenguaje. Pero es más frecuente que los productores se preocupen porque la audiencia no ha entendido el significado como ellos intentan transmitirlo. Lo que quieren decir es que los televidentes no están operando dentro del código “dominante”. Su ideal es el de una “comunicación perfectamente transparente”. En cambio, con lo que tienen que confrontarse es con una “comunicación simultáneamente distorsionada”.</p> 
<p>En los últimos años las discrepancias de este tipo han sido explicadas habitualmente refiriéndose a la “selección perceptiva”. Esta es la puerta a través de la cual el pluralismo residual evade las compulsiones de un proceso altamente estructurado, asimétrico y no equivalente. Por supuesto, habrá siempre lecturas privadas, individuales y variables. Pero “percepción selectiva” no es prácticamente nunca tan selectiva, casual o privada como el término parece sugerir.</p> 
<p>Los patrones, normas, exhiben a través de las variantes personales, confluencias. Y una nueva aproximación a los estudios de audiencia deberían comenzar con una crítica de la teoría de la “percepción selectiva”.</p> 
<p>Se argumentó antes que no existe correspondencia necesaria entre codificación y decodificación, la primera puede intentar dirigir pero no puede garantizar o prescribir la última que tiene sus propias condiciones de existencia. A no ser que sea dislocada, la codificación tendrá el efecto de construir alguno de los límites y parámetros dentro de los cuales operará la decodificación. Si no hubiera límites la audiencia podría simplemente leer lo que se le ocurriera en un mensaje. Sin duda existen algunos “malentendidos totales” de este tipo. Pero el espectro vasto debe contener algún grado de reciprocidad entre los momentos de codificación y decodificación, pues de lo contrario no podríamos establecer en absoluto un intercambio comunicativo efectivo. De cualquier forma esta “correspondencia” no está dada sino construida. No es “natural” sino producto de una articulación entre dos momentos distintivos. Y el primero no puede garantizar ni determinar, en un sentido simple, qué códigos de decodificación serán empleados. De lo contrario el circuito de la comunicación sería uno perfectamente equivalente, y cada mensaje sería una instancia de una “comunicación perfectamente transparente”.</p> 
<center>Página 7</center>
<span className="ind">1ling. Según Saussure, díc. de cada una de las relaciones que se pueden definir entre los elementos lingüísticos de la cadena hablada en la expresión. Díc. del proceso de segmentación jerárquica de un texto hasta el aislamiento en cada nivel de las unidades mínimas de la lengua.</span>
  </div>
    </div>
    );
}